### ISSUE TITLE
[Feature request] Support relative paths for directory icon paths

### ISSUE THREAD

**Issue by ItsDrike** [lxqt/libfm-qt#1019]
**Is your feature request related to a problem? Please describe.**
I sometimes like to override the thumbnail/icon of a directory with one of the images inside of it. I do this with the `.directory` files, specifically, like so:

```
[Desktop Entry]
Icon=/home/itsdrike/Media/Pictures/Wallpapers/active.png
```

However, the current implementation doesn't seem to allow using relative paths in this file, which is annoying, as I sometimes like setting these icons on external drives, which can get mounted in different ways, making absolute URLs not viable, also, absolute URLs cause annoyances when moving directories around even outside of external drives.

**Describe the solution you'd like**
It should be possible to specify a relative path in the `.desktop` file for `Icon`, e.g.:

```
[Desktop Entry]
Icon=./active.png
```

**Comment by tsujan** [comment]
> absolute URLs cause annoyances when moving directories around

Icon names can be used instead of paths/URLs.

Anyway, this is a valid feature request. I think it can be implemented by changing a single line of code; will look into it when I find the time.

**Comment by tsujan** [comment]
Done here: https://github.com/lxqt/libfm-qt/pull/1020
