### ISSUE TITLE
Please reduce the amount of exported symbols

### ISSUE THREAD

**Issue by agaida** [lxqt/libfm-qt#125]
##### Expected Behavior
only really needed symbols should be exported

##### Current Behavior
bloody mess describe it best - and this will cause havoc with every compiler/qt/whatever change

##### System Information
* Distribution & Version: current release

**Comment by agaida** [comment]
No bad will or so - our needed things will not break often, the rest will
https://buildd.debian.org/status/package.php?p=libfm-qt&suite=experimental

**Comment by tsujan** [comment]
How?

**Comment by agaida** [comment]
we should learn about - and i guess @luis-pereira and/or @palinek have a clue what to do in such cases.

**Comment by luis-pereira** [comment]
@agaida Can you give a example ? A symbol that shouldn't be there.

**Comment by tsujan** [comment]
@agaida @luis-pereira FYI, there are some libfm-qt source files that aren't used anywhere yet. They're created by PCMan to be completed later and shouldn't be removed.

**Comment by tsujan** [comment]
@agaida As for porting libfm functionalities to libfm-qt (our previous dicussion elsewhere), I checked some of the above-mentioned files and found gaps in them. PCMan should be aware of them and surely, he had a plan but filling in the gaps *may* be beyond my time. I might do it but no promise!

Anyhow, we still need parts of libfm and, since it isn't free of bugs, fast release schedules are needed. At least, a release is needed right now ;)

**Comment by palinek** [comment]
> .. A symbol that shouldn't be there.

Right, because the symbol visibility handling is already there... the `fm-qt_export.h`  is generated [here](https://github.com/lxde/libfm-qt/blob/master/src/CMakeLists.txt#L171), symbols are implicitly hidden (by using lxqt-build-tools compiler settings) and needed symbols are explicitly stated like e.g. [here](https://github.com/lxde/libfm-qt/blob/master/src/filemenu.h#L37):
```c++
class LIBFM_QT_API FileMenu : public QMenu {
```

Example of hidden [symbol](https://github.com/lxde/libfm-qt/blob/master/src/filemenu_p.h#L30):
```
~/work/oss/lxqt/libfm-qt/build$ objdump -T src/libfm-qt.so | c++filt | egrep AppInfoAction
~/work/oss/lxqt/libfm-qt/build$
```

**Comment by agaida** [comment]
Only a example: https://salsa.debian.org/lxqt-team/libfm-qt/blob/debian/sid/debian/libfm-qt3.symbols#L369-391 
The question with such symbols is: Do we really need them or can we just filter the export better - in general this is a question for nearly all arch-dep. Symbols. It is no fun if one maintain over 20 architectures and symbols change if the compiler or anything else change.

**Comment by tsujan** [comment]
> It is no fun if one maintain over 20 architectures...

Only a Debian problem?

I ask this because I'm curious: Doesn't that happen with any other library?

**Comment by agaida** [comment]
in the end not only a debian probelm - ok, there is no other distribution with nearly that amount of supported architectures - but one can see it different: We track these things and know exactly which packages need a rebuild etc if things change. 
And i still don't belive that this amount of exported symbols is needed - for examle:
* https://salsa.debian.org/lxqt-team/liblxqt/blob/debian/sid/debian/liblxqt0.symbols 292 lines
* https://salsa.debian.org/lxqt-team/libqtxdg/blob/debian/sid/debian/libqt5xdg3.symbols 141 lines
* https://salsa.debian.org/lxqt-team/libqtxdg/blob/debian/sid/debian/libqt5xdgiconloader3.symbols 23 lines
* https://salsa.debian.org/lxqt-team/libfm-qt/blob/debian/sid/debian/libfm-qt3.symbols #1465 lines -- really????

**Comment by tsujan** [comment]
> We track these things and know exactly which packages need a rebuild etc if things change.

Having had no experience in those areas, I understand your concerns now. However, I still don't know if this is specific to libfm-qt -- I mean in comparison to other libraries with similar jobs, not to other LXQt programs.

**Comment by luis-pereira** [comment]
@agaida I don't see how it's possible to reduce it. Took a look into it the stuff that's there should be there. I don't see how we can reduce it. libfm-qt is a "big" library.
While taking a look into lxqt-build-tools to check it, realized that we weren't setting `CMAKE_C_VISIBILITY_PRESET`. PR [here](https://github.com/lxde/lxqt-build-tools/pull/26). It won't make a big difference tough.

**Comment by palinek** [comment]
> I don't see how it's possible to reduce it. Took a look into it the stuff that's there should be there.

On the other hand, there are some private methods of public classes in the symbols table and we could decrease the amount by using the PIMPL idiom (the d-pointer in Qt world)

**Comment by luis-pereira** [comment]
@palinek There's no doubt about that. I was talking about applying build settings.

**Comment by agaida** [comment]
it would help a lot if we could get rid esp of things like
https://gcc.gnu.org/onlinedocs/libstdc++/libstdc++-html-USERS-4.3/a00821.html
* (c++)"std::_Sp_counted_ptr_inplace<Fm::Thumbnailer, std::allocator<Fm::Thumbnailer>,...
* (c++)"typeinfo for std::_Sp_counted_ptr_inplace<
* (c++)"typeinfo name for std::_Sp_counted_base<
*  (c++)"vtable for std::_Sp_counted_ptr_inplace<
(at least it would make me happy - all other things are more or less ok for me)

**Comment by palinek** [comment]
> it would help a lot if we could get rid esp of things like

These are the helpers if you/we use the std::shared_ptr/std::make_shared for a public (symbols exported) class.

**Comment by palinek** [comment]
An example of decreasing the shared_ptr\* symbols is as following (replacing the std::shared/weak_ptr by QShared/WeakPtr):
```diff
diff --git a/src/core/folder.cpp b/src/core/folder.cpp
index 66d4b7b..ebc5681 100644
--- a/src/core/folder.cpp
+++ b/src/core/folder.cpp
@@ -56,8 +56,8 @@ Folder::Folder():
     has_fs_info{false},
     defer_content_test{false} {
 
-    connect(volumeManager_.get(), &VolumeManager::mountAdded, this, &Folder::onMountAdded);
-    connect(volumeManager_.get(), &VolumeManager::mountRemoved, this, &Folder::onMountRemoved);
+    connect(volumeManager_.data(), &VolumeManager::mountAdded, this, &Folder::onMountAdded);
+    connect(volumeManager_.data(), &VolumeManager::mountRemoved, this, &Folder::onMountRemoved);
 }
 
 Folder::Folder(const FilePath& path): Folder() {
diff --git a/src/core/folder.h b/src/core/folder.h
index d2bbb76..f093648 100644
--- a/src/core/folder.h
+++ b/src/core/folder.h
@@ -159,7 +159,7 @@ private:
     std::vector<FileInfoJob*> fileinfoJobs_;
     FileSystemInfoJob* fsInfoJob_;
 
-    std::shared_ptr<VolumeManager> volumeManager_;
+    QSharedPointer<VolumeManager> volumeManager_;
 
     /* for file monitor */
     bool has_idle_reload_handler;
diff --git a/src/core/volumemanager.cpp b/src/core/volumemanager.cpp
index 522c38c..138cea1 100644
--- a/src/core/volumemanager.cpp
+++ b/src/core/volumemanager.cpp
@@ -3,7 +3,7 @@
 namespace Fm {
 
 std::mutex VolumeManager::mutex_;
-std::weak_ptr<VolumeManager> VolumeManager::globalInstance_;
+QWeakPointer<VolumeManager> VolumeManager::globalInstance_;
 
 VolumeManager::VolumeManager():
     QObject(),
@@ -31,11 +31,11 @@ VolumeManager::~VolumeManager() {
     }
 }
 
-std::shared_ptr<VolumeManager> VolumeManager::globalInstance() {
+QSharedPointer<VolumeManager> VolumeManager::globalInstance() {
     std::lock_guard<std::mutex> lock{mutex_};
     auto mon = globalInstance_.lock();
     if(mon == nullptr) {
-        mon = std::make_shared<VolumeManager>();
+        mon.reset(new VolumeManager);
         globalInstance_ = mon;
     }
     return mon;
diff --git a/src/core/volumemanager.h b/src/core/volumemanager.h
index 642adc8..5eff9b1 100644
--- a/src/core/volumemanager.h
+++ b/src/core/volumemanager.h
@@ -167,7 +167,7 @@ public:
         return mounts_;
     }
 
-    static std::shared_ptr<VolumeManager> globalInstance();
+    static QSharedPointer<VolumeManager> globalInstance();
 
 Q_SIGNALS:
     void volumeAdded(const Volume& vol);
@@ -228,8 +228,8 @@ private:
     std::vector<Volume> volumes_;
     std::vector<Mount> mounts_;
 
-    static std::mutex mutex_;
-    static std::weak_ptr<VolumeManager> globalInstance_;
+    static std::mutex Q_DECL_HIDDEN mutex_;
+    static QWeakPointer<VolumeManager> Q_DECL_HIDDEN globalInstance_;
 };
 
 } // namespace Fm
diff --git a/src/tests/test-volumemanager.cpp b/src/tests/test-volumemanager.cpp
index 7b6438a..319f04a 100644
--- a/src/tests/test-volumemanager.cpp
+++ b/src/tests/test-volumemanager.cpp
@@ -8,10 +8,10 @@ int main(int argc, char** argv) {
 
     auto vm = Fm::VolumeManager::globalInstance();
 
-    QObject::connect(vm.get(), &Fm::VolumeManager::volumeAdded, [=](const Fm::Volume& vol) {
+    QObject::connect(vm.data(), &Fm::VolumeManager::volumeAdded, [=](const Fm::Volume& vol) {
         qDebug() << "volume added:" << vol.name().get();
     });
-    QObject::connect(vm.get(), &Fm::VolumeManager::volumeRemoved, [=](const Fm::Volume& vol) {
+    QObject::connect(vm.data(), &Fm::VolumeManager::volumeRemoved, [=](const Fm::Volume& vol) {
         qDebug() << "volume removed:" << vol.name().get();
     });
 
```

...and this is an easy example... Is it worth?

**Comment by PCMan** [comment]
The number of symbols is quite normal for a medium-sized library.
That's part of the price we pay for using C++. Many symbols are generated by STL.
More symbols result in slower dynamic linking, but in most cases it's fast enough so I don't consider this a critical issue. Of course you can replace STL with some Qt classes, but that will make the code less reusable outside Qt even when it does not related to GUI. For this reason, I really prefer writing standard C++ rather than using their Qt counter parts.

**Comment by PCMan** [comment]
Using pimpl idiom can reduce some of the symbols and speed up compiling at the cost of increased memory allocation & worse data locality. Also, this can make the code less readable sometimes so I seldom use them. It doesn't really matter for non-performance critical code, though. If it really helps, we can change the code to use pimpl as appropriate.

**Comment by agaida** [comment]
If there is no easy way and clean way to get rid of - just forget it :) The main reason was that i'm not that eager to maintain constructs like that as they tend to break often:
```
 (c++|arch= !arm64 !armel !armhf !i386 !mips !mipsel !mips64el !ppc64el !alpha !hppa !hurd-i386 !kfreebsd-i386 !m68k !powerpc !ppc64 !sh4 !sparc64 !x32 )"std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > __gnu_cxx::__to_xstring<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char>(int (*)(char*, unsigned long, char const*, __va_list_tag*), unsigned long, char const*, ...)@Base" 0.12.0
 (optional|c++|arch= !amd64 !arm64 !armel !armhf !i386 !mips !mips64el !mipsel !ppc64el !s390x !hppa !kfreebsd-amd64 !kfreebsd-i386 !m68k !powerpc !ppc64 !sh4 !x32 )"std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > __gnu_cxx::__to_xstring<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char>(int (*)(char*, unsigned long, char const*, __va_list_tag), unsigned long, char const*, ...)@Base" 0.12.0
 (optional|c++|arch= !amd64 !arm64 !i386 !mips !mips64el !mipsel !ppc64el !s390x !alpha !hppa !hurd-i386 !kfreebsd-amd64 !kfreebsd-i386 !m68k !powerpc !ppc64 !sh4 !x32 )"std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > __gnu_cxx::__to_xstring<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char>(int (*)(char*, unsigned int, char const*, std::__va_list), unsigned int, char const*, ...)@Base" 0.12.0
 (optional|c++|arch= !amd64 !arm64 !armel !armhf !i386 !mips64el !ppc64el !s390x !alpha !hurd-i386 !kfreebsd-amd64 !kfreebsd-i386 !powerpc !ppc64 !sh4 !x32 )"std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > __gnu_cxx::__to_xstring<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char>(int (*)(char*, unsigned int, char const*, void*), unsigned int, char const*, ...)@Base" 0.12.0
 (optional|c++|arch= !amd64 !arm64 !armel !armhf !i386 !mips !mips64el !mipsel !s390x !alpha !hppa !kfreebsd-amd64 !kfreebsd-i386 !m68k !powerpc !sh4 !x32 )"std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > __gnu_cxx::__to_xstring<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char>(int (*)(char*, unsigned long, char const*, char*), unsigned long, char const*, ...)@Base" 0.12.0
 (optional|c++|arch= !amd64 !arm64 !armel !armhf !mips !mipsel !mips64el !ppc64el !s390x !alpha !kfreebsd-amd64 !hppa !m68k !powerpc !ppc64 !sh4 !sparc64 !x32 )"std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > __gnu_cxx::__to_xstring<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char>(int (*)(char*, unsigned int, char const*, char*), unsigned int, char const*, ...)@Base" 0.12.0
 (optional|c++|arch= !amd64 !arm64 !armel !armhf !i386 !mips !mips64el !mipsel !ppc64el !s390x !alpha !hppa !kfreebsd-amd64 !kfreebsd-i386 !m68k !ppc64 !sh4 )"std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > __gnu_cxx::__to_xstring<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char>(int (*)(char*, unsigned int, char const*, __va_list_tag*), unsigned int, char const*, ...)@Base" 0.12.0
 (optional|c++|arch= !amd64 !arm64 !armel !armhf !i386 !mips !mips64el !mipsel !ppc64el !s390x !alpha !hppa !kfreebsd-amd64 !kfreebsd-i386 !m68k !powerpc !ppc64 !x32)"std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > __gnu_cxx::__to_xstring<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char>(int (*)(char*, unsigned int, char const*, __va_list_tag), unsigned int, char const*, ...)@Base" 0.12.0
 (optional|c++|arch= !amd64 !arm64 !armel !armhf !i386 !mips !mipsel !ppc64el !s390x !alpha !hppa !kfreebsd-amd64 !kfreebsd-i386 !m68k !powerpc !ppc64 !sh4 !x32 )"std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > __gnu_cxx::__to_xstring<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char>(int (*)(char*, unsigned long, char const*, void*), unsigned long, char const*, ...)@Base" 0.12.0
 (optional|c++|arch= !amd64 !armel !armhf !i386 !mips !mipsel !mips64el !ppc64el !s390x !alpha !hppa !hurd-i386 !kfreebsd-amd64 !kfreebsd-i386 !m68k !powerpc !ppc64 !sh4 !sparc64 !x32 )"std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > __gnu_cxx::__to_xstring<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char>(int (*)(char*, unsigned long, char const*, std::__va_list), unsigned long, char const*, ...)@Base" 0.12.0
```
