### ISSUE TITLE
copied filename from google drive is wrong

### ISSUE THREAD

**Issue by damianatorrpm** [lxqt/libfm-qt#137]
##### Expected Behavior
Copy google-drive://YOURACCOUNT@gmail.com/testfile.txt
 to /home/you/testfile.txt
Have  /home/you/testfile.txt
##### Current Behavior
Copy google-drive://YOURACCOUNT@gmail.com/testfile.txt
 to /home/you/testfile.txt
Have  /home/you/GARBAGENAMEXYA432yhtghfdfvdaew3SDFD

##### Possible Solution
Problem occurs using libfm-qt directly and with pcmanfm-qt
https://debarshiray.wordpress.com/2015/09/13/google-drive-and-gnome-what-is-a-volatile-path/
the #GarbageName is the "real one" meaning the one non-gvfs capable applications see while browsing
/run/user/1000/gvfs/yourdriveaccount/

**Comment by tsujan** [comment]
Do you know a way other than installing gnome-control-center for testing this? I don't want this amount of gnome garbage on my system:

```
Packages (33) bolt-0.8-2  cheese-3.34.0-2  clutter-1.26.2-2
              clutter-gst-3.0.27-2  clutter-gtk-1.8.4-1  cogl-1.22.4-1
              colord-gtk-0.2.0-1  frei0r-plugins-1.7.0-1  gavl-1.4.0-3
              gnome-bluetooth-3.34.0+1+g96295afd-1  gnome-color-manager-3.32.0-2
              gnome-desktop-1:3.34.2-1  gnome-settings-daemon-3.34.2-1
              gnome-video-effects-0.5.0+4+g9554041-1  grilo-0.3.11-1
              gsound-1.0.2-4  libgnomekbd-3.26.1+2+g8d02ebd-1
              libgweather-3.34.0-1  libhandy-0.0.13-1  libnma-1.8.24-1
              libquvi-0.9.4-5  libquvi-scripts-0.9.20131130-4
              lua52-bitop-1.0.2-8  lua52-expat-1.3.0-4  lua52-lpeg-1.0.2-1
              lua52-luajson-1.3.4-2  lua52-socket-20190219-1
              nm-connection-editor-1.8.24-1  shared-color-targets-0.1.7-2
              totem-pl-parser-3.26.4-1  vte-common-0.58.3-1  vte3-0.58.3-1
              gnome-control-center-3.34.2-1
```

**Comment by damianatorrpm** [comment]
It is not possible at this point.
I opened a bug report for this in GNOME bugtracker: I wanted to use gio add drive 
As google drive needs an OAuth token which is obtrained via a Webframe showing google authentication and currently only gnome-control-center provides this (which I am fine with as I use gnome-session and gnome-control-center)

**Comment by tsujan** [comment]
> It is not possible at this point.

I might try the Gnome installation I have on another machine. But I don't update anything on it because its older Qt version has been very useful for detecting (and working around) new Qt bugs and Arch-based system don't have partial upgrades. So, I could do it only if all needed packages are already installed. Will test it later...

> As google drive needs an OAuth token

I know. I used `rclone` without problem but it's very different.

**Comment by tsujan** [comment]
Update:

Unfortunately, `gnome-control-center` crashes on my second computer and I don't want an upgrade there. But playing will theories is still possible ;)

**Comment by damianatorrpm** [comment]
@tsujan Actually you can try the same problem is also if you copy a file from recent://

**Comment by tsujan** [comment]
> Actually you can try the same problem is also if you copy a file from recent://

Good.

**Comment by tsujan** [comment]
OK, this can be easily done by using `g_file_info_get_display_name()` because we get the `GFileInfo` when transferring files. Since gnome uses GLib in that way, I don't think any problem will happen but *our* display name shouldn't be used because we treat desktop files in a special way (unlike gnome devs, we want to have a usable desktop).

So, more tests are needed before making a PR.

**Comment by tsujan** [comment]
This and https://github.com/lxqt/libfm-qt/issues/138 are closely related to each other because of the new "display name" approach. So, I might make a single PR for both.

**Comment by tsujan** [comment]
@damianatorrpm This should work (it works with recent:///): https://github.com/lxqt/libfm-qt/pull/511

It also fixes https://github.com/lxqt/libfm-qt/issues/138

If you test it, please confirm!

**Comment by damianatorrpm** [comment]
@tsujan Yes this fixes all google-drive copy/move/rename related bugs
I also tested with recent also everything fixed. 

One small thing though:
```c++
    // use GIO's display name if existing; otherwise, for example,
    // the files in recent:/// will be transferred with their real names
    const char* destDisplayName = g_file_info_get_display_name(srcInfo.get());
```
Could be:

```c++
    // use GIO's display name if existing; otherwise, for example,
    // the files in recent:/// will be transferred with their real names

    //remove this comment below
    //if (Q_UNLIKELY(g_strstr_len(destDisplayName, -1, "/") != nullptr))

    QString destDisplayNameString = g_file_info_get_display_name(srcInfo.get());

    if (Q_UNLIKELY(destDisplayNameString.contains("/")))
        destDisplayNameString.replace("/", "-");

    const char* destDisplayName = destDisplayNameString.toUtf8().constData();
```

Yes it is possible that on google-drive backend (but maybe others now or in the future)
the displayname contains `/` nautilus behaviour is to replace `/` with `-`

Currently it says 

> Permission denied. 

Fair enough to fail in the slash case but the error message is wrong.
I do think that gvfs will provide maybe more cloud providers or backends
that may allow this.

**Comment by tsujan** [comment]
@damianatorrpm  Thanks for testing the PR!

Slash is a forbidden character in file names but I'll investigate what you mentioned. If slash can be used in display names, we could replace it with ["fraction slash"](https://en.wikipedia.org/wiki/Slash_(punctuation)#Fractions), which looks like a slash but isn't one: `⁄`.
