### ISSUE TITLE
Wrong namespace on document element in libfm-qt-mimetypes.xml

### ISSUE THREAD

**Issue by yan12125** [lxqt/libfm-qt#174]
##### Expected Behavior
Nothing special happens during package upgrading/installation

##### Current Behavior
Arch Linux's pacman use hooks to handle common works across multiple packages. When it's processing libfm-qt-mimetypes.xml, an error occurs:
```
$ sudo pacman -Syu                      
(...irrelevant stuff...)
:: Running post-transaction hooks...
(1/4) Updating icon theme caches...
(2/4) Arming ConditionNeedsUpdate...
(3/4) Updating the desktop file MIME type cache...
(4/4) Updating the MIME type database...
Wrong namespace on document element in '/usr/share/mime/packages/libfm-qt-mimetypes.xml' (should be http://www.freedesktop.org/standards/shared-mime-info)
```

##### Possible Solution
Switch back to http:// in data/libfm-qt-mimetypes.xml

The shared-mime-info spec [1] states that the namespace must be http://www.freedesktop.org/standards/shared-mime-info

[1] https://specifications.freedesktop.org/shared-mime-info-spec/0.18/ar01s02.html#idm139750563085760

##### Steps to Reproduce (for bugs)
1. ```sudo /usr/bin/update-mime-database /usr/share/mime``` (This is the actual command [1] used in the last pacman hook)

[1] https://git.archlinux.org/svntogit/packages.git/tree/trunk/update-mime-database.hook?h=packages/shared-mime-info

##### Context
I'm doing a usual package upgrade

##### System Information
* Distribution & Version: Arch Linux x86_64 latest
* Kernel: 4.15.8-1
* Qt Version: 5.10.1-7
* lxqt-build-tools Version: git
* libqtxdg Version: git
* Package version: git

Ref: #173
/cc @agaida

**Comment by agaida** [comment]
yes - no problem

**Comment by tsujan** [comment]
@agaida Thanks!

@yan12125 Thank you for seeing it!
