### ISSUE TITLE
[Qt 5.11] PCManFM-Qt Segfaults in 'libfm-qt'

### ISSUE THREAD

**Issue by Chiitoo** [lxqt/libfm-qt#175]
This may well be more in PCManFM-Qt, rather than libfm-qt, but since the segfault happens in libfm-qt, I decided to file this here.

##### Expected Behavior
No segmentation faults occur.

##### Current Behavior
When copying something such as text or a file in an application, such as Konsole or the PCManFM-Qt file manager, the pcmanfm-qt process crashes with a segmentation fault in 'folderview.h' (another crash occurs when said application is terminated):

```
#0  Fm::FolderView::folder (this=0x55df7fa75800)
    at libfm-qt-9999/src/folderview.h:87
#1  Fm::FolderView::onClipboardDataChange (this=0x55df7fa75800)
    at libfm-qt-9999/src/folderview.cpp:1350
#2  0x00007f7d941705c2 in QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>,
  void, void (Fm::FolderView::*)()>::call(void (Fm::FolderView::*)(), Fm::FolderView*, void**)
  (arg=<optimized out>, o=<optimized out>, f=<optimized out>)
    at /usr/include/qt5/QtCore/qobjectdefs_impl.h:134
#3  QtPrivate::FunctionPointer<void (Fm::FolderView::*)()>::call<QtPrivate::List<>,
  void>(void (Fm::FolderView::*)(), Fm::FolderView*, void**) (arg=<optimized out>,
  o=<optimized out>, f=<optimized out>)
    at /usr/include/qt5/QtCore/qobjectdefs_impl.h:167
#4  QtPrivate::QSlotObject<void (Fm::FolderView::*)(), QtPrivate::List<>, void>::impl(int,
  QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) (which=<optimized out>,
  this_=<optimized out>, r=<optimized out>, a=<optimized out>, ret=<optimized out>)
    at /usr/include/qt5/QtCore/qobjectdefs_impl.h:396
#5  0x00007f7d92b6d57a in QtPrivate::QSlotObjectBase::call (a=0x7ffc1e4a08d0, r=0x55df7fa75800,
  this=0x55df7fa983a0)
    at qtcore-5.11.9999/src/corelib/kernel/qobjectdefs_impl.h:376
#6  QMetaObject::activate (sender=sender@entry=0x55df7fb300c0, signalOffset=<optimized out>, 
    local_signal_index=local_signal_index@entry=3, argv=argv@entry=0x0)
    at qtcore-5.11.9999/src/corelib/kernel/qobject.cpp:3754
#7  0x00007f7d92b6da26 in QMetaObject::activate (sender=0x55df7fb300c0,
  m=m@entry=0x7f7d9364f4e0 <QClipboard::staticMetaObject>,
  local_signal_index=local_signal_index@entry=3, argv=argv@entry=0x0)
    at qtcore-5.11.9999/src/corelib/kernel/qobject.cpp:3633
#8  0x00007f7d93380ee6 in QClipboard::dataChanged (this=<optimized out>)
    at .moc/moc_qclipboard.cpp:181
#9  0x00007f7d930aab3d in QClipboard::emitChanged (this=0x55df7fb300c0,
  mode=mode@entry=QClipboard::Clipboard)
    at qtgui-5.11.9999/src/gui/kernel/qclipboard.cpp:595
#10 0x00007f7d93090981 in QPlatformClipboard::emitChanged (this=this@entry=0x7f7d80007010, 
mode=mode@entry=QClipboard::Clipboard)
    at qtgui-5.11.9999/src/gui/kernel/qplatformclipboard.cpp:125
```

##### Possible Solution
This starts happening with the following commits:

  https://github.com/lxqt/libfm-qt/commit/aa7d86e0361ca5424dfacb62641b9b087959a744
  https://github.com/lxqt/pcmanfm-qt/commit/9458ba41d94327ab833e1134d76c4eb67a7a799b

##### Steps to Reproduce (for bugs)
1. Run LXQt at current git master (or at least with the aforementioned changes), with Qt 5.11 (tested as far back as beta3, which did not seem to make a difference yet, but on another machine, probably not surprisingly, did not see this with Qt 5.9.5).
2. Launch a terminal emulator, such as Konsole.
3. Copy text from said terminal emulator.

Alternatively:

1. Same as before.
2. Launch the PCManFM-Qt file manager.
3. Copy a file by some means, such as using the right-click context-menu.

##### Context
Since I haven't used PCManFM-Qt for file managing in recent times due to issue 164 [1], I only noticed this due to the background image of mine disappearing, and returning while the 'pcmanfm-qt' process segfaults and restarts.

1. https://github.com/lxqt/libfm-qt/issues/164

##### System Information
* Distribution & Version: Gentoo Linux
* Kernel: 4.15.15
* Qt Version: 5.11 (http://code.qt.io/cgit/qt/qtbase.git/commit/?id=2b5587d901a0cc23749bf27a923d50bf0e5860d3)
* lxqt-build-tools Version: https://github.com/lxqt/lxqt-build-tools/commit/edd620d5123fed10e9e2787fed743deea95606eb
* libqtxdg Version: https://github.com/lxqt/libqtxdg/commit/b5ddbd4bb9ec62b3ddc954cb41b06ca59ed1f9cb

**Comment by tsujan** [comment]
Never happens here, with Qt 5.10.1. Qt 5.11 is still unstable and not reliable for finding bugs.

**Comment by tsujan** [comment]
I add the obvious: Qt 5.11 should come into our distros for us to build the whole LXQt against it and see whether there is any problem.

**Comment by agaida** [comment]
Right - and i agree that these tests are important - regression testing and fixing before a new Qt release is rolled out would be a completely new and cool thing.

**Comment by Chiitoo** [comment]
Yeah, I had a feeling you're still not too interested in these.

Unsure if these should keep open or not 'til that time comes; I'll leave that to you, and I imagine there's no point in pull requests for build failures due to missing headers either?

Thanks!

**Comment by tsujan** [comment]
> Yeah, I had a feeling you're still not too interested in these.

We'll be definitely interested if they happen with a stable Qt 5.11. It's still too soon; Hence leaving them open.

**Comment by agaida** [comment]
@Chiitoo - and it would be nice if you would place your findings in the Qt bugtracker too

**Comment by tsujan** [comment]
I believe that this is the same as https://github.com/lxqt/libfm-qt/issues/164. So, closing it, for now.
