### ISSUE TITLE
Potential fall through

### ISSUE THREAD

**Issue by agaida** [lxqt/libfm-qt#176]

**Comment by agaida** [comment]
libfm-qt/src/foldermodel.cpp: In member function ‘virtual bool Fm::FolderModel::dropMimeData(const QMimeData*, Qt::DropAction, int, int, const QModelIndex&)’:
libfm-qt/src/foldermodel.cpp:438:40: warning: this statement may fall through [-Wimplicit-fallthrough=]
             FileOperation::symlinkFiles(srcPaths, destPath);
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
libfm-qt/libfm-qt/src/foldermodel.cpp:439:9: note: here
         default:
         ^~~~~~~

**Comment by agaida** [comment]
```
libfm-qt/src/folderview.cpp: In member function ‘virtual bool Fm::FolderView::eventFilter(QObject*, QEvent*)’:
libfm-qt/src/folderview.cpp:1053:13: warning: this statement may fall through [-Wimplicit-fallthrough=]
             }
             ^
libfm-qt/src/folderview.cpp:1054:9: note: here
         case QEvent::HoverLeave:
         ^~~~
```

**Comment by tsujan** [comment]
A case of https://github.com/lxqt/lxqt/issues/1318 . I'm aware of them; they're harmless.

**Comment by agaida** [comment]
Damn, i was forced to have a look onto libfm-qt and make some symbols stuff for riscv64 - didn't check the current code :D

**Comment by tsujan** [comment]
From that page:

> /<<PKGBUILDDIR>>/src/core/fileinfo.cpp:132:21: warning: this statement may fall through [-Wimplicit-fallthrough=]

It should be me who added that `/* Falls through. */` at fileinfo.cpp:134 -- my memory isn't good with boring jobs ;) It seems that such cases are fixed in libfm-qt.

**Comment by palinek** [comment]
From C++17 there is the `[[fallthrough]]` attribute for such cases http://en.cppreference.com/w/cpp/language/attributes
