### ISSUE TITLE
menu-cache should be optional

### ISSUE THREAD

**Issue by agaida** [lxqt/libfm-qt#185]
default to off - only a reminder

**Comment by PCMan** [comment]
It's required at the moment.
The application chooser dialog and menu:// URIs are using that library.
Unless we make these related features optional it's hard to remove.

**Comment by agaida** [comment]
right now the dependency don't hurt - we removed the big impact of menu-cache in the panel. But it would be fine to get rid of menu-cache completely.

**Comment by tsujan** [comment]
→ https://github.com/lxqt/libfm-qt/issues/417
