### ISSUE TITLE
(Harmless?) error message with file dialog

### ISSUE THREAD

**Issue by tsujan** [lxqt/libfm-qt#225]
##### Steps to Reproduce (for bugs)

1. Open a Qt app that uses native file dialogs from a terminal emulator.
2. Open a file dialog from that app.
3. Enter a valid path into its path bar (after making it editable).
4. Press ENTER.

Then, this message will appear in the terminal: `QCoreApplication::postEvent: Unexpected null receiver`. The file dialog will work fine though.

##### Possible Solution

Should see which event is sent to a null receiver, of course.

##### Context

I don't know if this existed before or happens with Qt 5.11.

##### System Information

Qt 5.11.1 + Latest git LXQt

**Comment by Fat-Zer** [comment]
It's not only about file dialogs, I can reproduce the same thing with pcmanfm-qt.

Backtrace:
```
#0  0x00007ffff3cc2da0 in write () from /lib64/libc.so.6
#1  0x00007ffff3c4eddd in _IO_file_write () from /lib64/libc.so.6
#2  0x00007ffff3c4df92 in new_do_write () from /lib64/libc.so.6
#3  0x00007ffff3c4f63e in _IO_file_xsputn () from /lib64/libc.so.6
#4  0x00007ffff3c22c08 in buffered_vfprintf () from /lib64/libc.so.6
#5  0x00007ffff3c1fd1e in vfprintf () from /lib64/libc.so.6
#6  0x00007ffff3ce4195 in __fprintf_chk () from /lib64/libc.so.6
#7  0x00007ffff47c532d in ?? () from /usr/lib64/libQt5Core.so.5
#8  0x00007ffff47c0377 in ?? () from /usr/lib64/libQt5Core.so.5
#9  0x00007ffff47c0488 in ?? () from /usr/lib64/libQt5Core.so.5
#10 0x00007ffff47ad07d in QMessageLogger::warning(char const*, ...) const () from /usr/lib64/libQt5Core.so.5
#11 0x00007ffff4965b63 in QCoreApplication::postEvent(QObject*, QEvent*, int) () from /usr/lib64/libQt5Core.so.5
#12 0x00007ffff7b72b94 in Fm::PathBar::closeEditor() () from /usr/lib64/libfm-qt.so.6
#13 0x00007ffff498c46e in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib64/libQt5Core.so.5
#14 0x00007ffff57436a5 in ?? () from /usr/lib64/libQt5Widgets.so.5
#15 0x00007ffff498c119 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib64/libQt5Core.so.5
#16 0x00007ffff5749df7 in QWidgetLineControl::processKeyEvent(QKeyEvent*) () from /usr/lib64/libQt5Widgets.so.5
#17 0x00007ffff573ceea in QLineEdit::keyPressEvent(QKeyEvent*) () from /usr/lib64/libQt5Widgets.so.5
#18 0x00007ffff5646387 in QWidget::event(QEvent*) () from /usr/lib64/libQt5Widgets.so.5
#19 0x00007ffff5742f02 in QLineEdit::event(QEvent*) () from /usr/lib64/libQt5Widgets.so.5
#20 0x00007ffff56063bc in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib64/libQt5Widgets.so.5
#21 0x00007ffff560ed17 in QApplication::notify(QObject*, QEvent*) () from /usr/lib64/libQt5Widgets.so.5
...
```

It happens inside `Fm::PathBar::closeEditor()` because  `tempPathEdit_->setVisible(false)` causes `editingFinished()` signal which causes yet another `closeEditor()` recursive call. This call resets `tempPathEdit_` to `nullptr` and when control later returned to top `closeEditor()` call on line`tempPathEdit_->deleteLater()` `tempPathEdit_` already is zero.

The simplest thing is to disconnect or block signals before hiding the widget.

**Comment by Fat-Zer** [comment]
@tsujan, the backtrace is not about a crash, it's about the message print as described on the issue...

**Comment by tsujan** [comment]
All right. The old code shouldn't cause a crash logically, as it didn't is practice.
