### ISSUE TITLE
File Dialog may become fullscreen with some WMs

### ISSUE THREAD

**Issue by tsujan** [lxqt/libfm-qt#244]
In which case, it couldn't be resized or made un-fullscreen.

I haven't encountered this issue with KWin or Compiz-reloaded but @agaida has (with xfwm4?).

**Comment by agaida** [comment]
i has - but it is so absurd that i have to make some more tests :)

**Comment by tsujan** [comment]
I'me sure you know that nothing is absurd (Murphy's law).

**Comment by tsujan** [comment]
Preventing the fullscreen state is easy and should be done for small screens. I'll make a PR after https://github.com/lxqt/libfm-qt/pull/243 is merged.

**Comment by tsujan** [comment]
OK, trying to prevent a fullscreen state wasn't a good idea in the first place. I just added the fullscreen/unfullscreen shortcut at https://github.com/lxqt/libfm-qt/pull/249

**Comment by tsujan** [comment]
Closing. See https://github.com/lxqt/libfm-qt/pull/249#issuecomment-411941468
