### ISSUE TITLE
Usage of mempcpy in core/thumbnalijob.cpp

### ISSUE THREAD

**Issue by BabylonAS** [lxqt/libfm-qt#297]
The file [core/thumbnailjob.cpp](https://github.com/lxqt/libfm-qt/blob/master/src/core/thumbnailjob.cpp) features the use of `mempcpy(3)` function on [line 99](https://github.com/lxqt/libfm-qt/blob/master/src/core/thumbnailjob.cpp#L99). This particular function is a non-standard extension by GNU, which may cause concerns regarding compatibility and is already the reason why `libfm-qt` refuses to compile on FreeBSD when built from this very repository by `clang` (however, there is a FreeBSD package and port available).

##### Possible Solution
1. Replace `mempcpy` with an applicable function from the Standard C Library. I don’t quite know what exactly makes `mempcpy` special, but right now I see `memmove` as the closest alternative.
2. Provide information on how to enable GNU extensions on Clang. If this solution fails, this might mean that I have to use glibc and `gcc`...

##### System Information

* Distribution & Version: FreeBSD 1.12-RELEASE (i386)
* Compiler: clang (LLVM 6.0)

**Comment by BabylonAS** [comment]
After examining the `mempcpy` source code at [Sourceware](https://sourceware.org/git/?p=glibc.git;a=blob_plain;f=string/mempcpy.c;hb=refs/heads/release/2.27/master), I find that it offers no advantages over basic `memcpy`, therefore I am submitting a pull request.

**Comment by agaida** [comment]
fixed in lxqt/libfm-qt/pull/298
