### ISSUE TITLE
libfm-qt, GLib and xterm

### ISSUE THREAD

**Issue by tsujan** [lxqt/libfm-qt#309]
libfm-qt is based on GLib and GLib uses a hard-coded list of terminal emulators to open apps inside terminal with desktop files that have `Terminal=true`. On that list, `gnome-terminal` is on the top and `xterm` is the fallback.

`xterm` is installed by default in some distros (Manjaro included), so that their users don't have any problem with such desktop files inside pcmanfm-qt. `xterm` can also be recommended by LXQt.

However, the ideal solution would be adding a workaround to libfm-qt or pcmanfm-qt, so that the same terminal emulator that's opened with `F4` is also used in such cases.

**Comment by PCMan** [comment]
No. Libfm brings its own implementation for this so we are not affected by this issue.

**Comment by tsujan** [comment]
@PCMan But we use libfm-qt.

**Comment by tsujan** [comment]
Here, they are treated in the same way and given to GLib:

https://github.com/lxqt/libfm-qt/blob/00dfbd0062d722c54cd253c88fe5137a623172cd/src/core/basicfilelauncher.cpp#L198

So, the workaround exists but isn't used?
