### ISSUE TITLE
Preferences for File Dialog

### ISSUE THREAD

**Issue by Fat-Zer** [lxqt/libfm-qt#349]
Currently there is no way to configure file dialog's icon size in Icon/Thumbnail/Compact filesystem view like it is possible in pcamnfmqt. Could we make it configurable?
I believe the best way would be to share the setting with pcmanfm-qt. If so, what exact way do you prefer? Use settings directly from pcmanfm's config or move them to a different location somewhere bellow `~/.config/lxqt/`?

**Comment by tsujan** [comment]
> I believe the best way would be to share the setting with pcmanfm-qt.

No!

> If so, what exact way do you prefer? 

It isn't a matter of preference. It already has its config.

**Comment by tsujan** [comment]
There is a way of adding a small Preferences dialog without cluttering the GUI: a Preferences menu-item can be added to the right-click menu(s). Then the icon sizes and the default view cold be configured in it (probably among other things).

There are still open issues that will take my time; so, I give this a low priority. But if you can do it in the above-mentioned way, be my guest!

**Comment by Fat-Zer** [comment]
Ok, would it be fine to embed it directly to the context menu of `Fm::FolderView` (when clicked on empty space, not a file, the `Fm::FolderMenu` (or modified it inside `Fm::FolderView::prepareFolderMenu()`)) e.g. after `Sorting`?

Also do you have anything against changing the iconSize on the fly with Ctrl+mouseWheelScroll?

**Comment by tsujan** [comment]
> ... when clicked on empty space...

Exactly.

> ... e.g. after Sorting?

No, at the end and after a separator, like the desktop context menu (something like `Dialog Preferences`, instead of `Desktop Preferences`) .

> Also do you have anything against changing the iconSize on the fly with Ctrl+mouseWheelScroll?

Provided that it's like a temporary zooming out/in and isn't written to the config file (like in FeatherPad), it's a good idea: the Preferences size is the default and the mouse wheel can zoom the contents. Then, you'll also have to implement `Ctrl+=`/`Ctrl++` (both), `Ctrl+-` and `Ctrl+0` (for unzooming == back to default).

**Comment by tsujan** [comment]
Oh, although I think you know it but just for the sake of clarity: the Preferences menu item should be added inside`filedialog.cpp`, not `folderview.cpp`.

**Comment by tsujan** [comment]
Dear members, contributors and active users:

In the latest git, LXQt file dialog remembers sorting, showing of hidden files, and hidden side-pane places. It already remembered its size and view mode.

In addition, I've made a patch for showing/hiding item thumbnails and tooltips by adding a menu button and moving all view options to its menu, as in the following screenshot:

![menu_button](https://user-images.githubusercontent.com/981076/91502700-f68be080-e8dd-11ea-9417-f4a36bd33dab.png)

This takes care of most options without cluttering the GUI (icon sizes might be added later, somehow, but IMO, they aren't important). The menu button also saves space on the toolbar.

Is there any objection to this?

**Comment by palinek** [comment]
> Is there any objection to this?

No. IMO this is a good way.

**Comment by tsujan** [comment]
One step further and icon sizes are also covered without needing a preferences dialog:

![icon_sizes](https://user-images.githubusercontent.com/981076/91629331-5fa64d80-e9dd-11ea-82e9-d2abf1ebe644.png)

Will make a PR after testing it.

**Comment by J-Dunn** [comment]
> In the latest git, LXQt file dialog remembers sorting, showing of hidden files, and hidden side-pane places. It already remembered its size and view mode.

This is great news. 
What version is "latest" in this context?  I have lxqt 0.15.0 on Fedora 33  which shows (c) date 2010- 2021, so presumably post-dates this info. However, I do not see the spanner icon for settings. 

I just upgraded from Fed 32 and I am finding this constantly annoying in that is does not hold changes, which suggests it was working better before and has lost settings I was used to and is not storing anything I set up. The update did mess with a few things so it maybe just file location changes of Fedora stamping on my config files. 

One thing I find really annoying is the displayed columns in detailed file view. If I right-click on any column heading I can configure what columns show ( eg get rid of the moronic "Types" column that eats space to state the bleeding obvious). 

I can deactivate this column but it is back to bug me next time I need to use the dlg.  Same for Auto-resize. 

Not much point in configuring these options ( which is cool ) if they get forgotten straight away. 

Am I on a recent enough version? 

Thanks.

**Comment by tsujan** [comment]
> I have lxqt 0.15.0

It's outdated.

**Comment by Kein** [comment]
> It isn't a matter of preference. It already has its config.

Where is its config?

**Comment by tsujan** [comment]
~/.config/lxqt/filedialog.conf

**Comment by Kein** [comment]
Thanks. Where can I find all available config options for that?

**Comment by tsujan** [comment]
Like with any other app, either by changing the GUI options and guessing the meanings of keys and values inside the config file or, if you're a developer, by reading the code.

Config files are for apps, not for users.

**Comment by Kein** [comment]
Filepicker dialogue has no GUI options to change, only view modes.

**Comment by tsujan** [comment]
What's "Filepicker"? We're talking about LXQt File Dialog, and it has several options.

If your LXQt File Dialog doesn't have any option, you have an outdated version.

**Comment by Kein** [comment]
LXQt File Dialog does not have an ability to be consistent with my pcmanfm settings and viewmodes.

**Comment by tsujan** [comment]
It has nothing to do with pcmanfm-qt.

**Comment by hemkr** [comment]
Thumbnails 4mb is the default in file dialog.
My picture is 15mb, so it cannot be displayed.
Could you let me set the file size?

**Comment by stefonarch** [comment]
In PCmanfm-qt → preferences thumbnails you can rise the limit.

**Comment by hemkr** [comment]
Okay thanks. But not more than 4mb in Chrome.
![screen-2023-01-30-17-37-33](https://user-images.githubusercontent.com/4699846/215427912-ab65a421-0bf4-4b00-a72c-5c186f1aca4a.jpg)

**Comment by tsujan** [comment]
The default limit is 4MiB, and LXQt file dialog doesn't have a setting for that. Being a file dialog, it isn't its job, but it might be added later.

**Comment by Trust2k** [comment]
In general, the year is already 2026, and there is still no setting for selecting the maximum thumbnail size in the file selection dialog box, @tsujan, please do it!

**Comment by tsujan** [comment]
Already answered in https://github.com/lxqt/libfm-qt/issues/877#issuecomment-2747935288. The year is irrelevant.

**Comment by Trust2k** [comment]
Regarding this limitation (4mb), I will still speak out. I understand that this decision has a certain logic, but I cannot accept the fact that it hinders basic user scenarios, such as choosing a photo in a messenger from a large number of photos.

https://github.com/user-attachments/assets/bb6e8669-28da-46ff-9219-8c4ab6f53c12

**Comment by Trust2k** [comment]
@tsujan instead of giving explanations, I could have written directly "I'm too lazy to rewrite a bunch of code for such a small thing."
