### ISSUE TITLE
[compiling] 0.14.0 libfm-qt.pc is not generated correctly in Fedora

### ISSUE THREAD

**Issue by sztsian** [lxqt/libfm-qt#350]
##### Context

I am packaging lxqt 0.14.0 into Fedora.
After libfm-qt 0.14.0 packaged, the libfm-qt.pc contains invalid line

##### System Information

* Distribution & Version:  Fedora Rawhide ( currently Rawhide is Fedora 30 )
* Kernel: it shouldn't matter. 
* Qt Version: 5.11.3
* lxqt-build-tools Version: 0.6.0
* libqtxdg Version: 3.3.0
* Package version: 0.14.0
All other versions are available in
https://copr-be.cloud.fedoraproject.org/results/zsun/test/fedora-rawhide-x86_64/00850682-libfm-qt/root.log.gz

##### Expected Behavior

The /usr/lib64/pkgconfig/libfm-qt.pc should be something like

> prefix=/usr
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include
>
> Name: libfm-qt
Description: A Qt/glib/gio-based lib used to develop file managers providing some file management utilities.
URL: https://github.com/lxqt/libfm-qt
Requires: Qt5Widgets Qt5X11Extras
Version: 0.14.0
Libs: -L${libdir} -lfm-qt
Cflags: -I${includedir}

##### Current Behavior

> prefix=/usr
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include
> 
> Name: libfm-qt
Description: A Qt/glib/gio-based lib used to develop file managers providing some file management utilities.
URL: https://github.com/lxqt/libfm-qt
**Requires: Qt5Widgets >=  Qt5X11Extras >=**
Version: 0.14.0
Libs: -L${libdir} -lfm-qt
Cflags: -I${includedir}

See the `Requires:` line!
With this, the rpm will require `pkgconfig(>=)` which will definitely fail in install.

##### Possible Solution

I don't know about cmake or .pc file. But I suggest to remove the `>=` should work.

##### Steps to Reproduce (for bugs)

1.  Find a Fedora Rawhide virtual machine
2.  Enable my playground with `dnf copr enable zsun/lxqt `
3.  Rebuild the srpm https://copr-be.cloud.fedoraproject.org/results/zsun/test/fedora-rawhide-x86_64/00850682-libfm-qt/libfm-qt-0.14.0-1.fc30.src.rpm
4. Try to install the generated rpm, or extract the libfm-qt.pc file from it and check like above

##### Additional info

If you prefer to read the whole rpm build log, here it is
https://copr-be.cloud.fedoraproject.org/results/zsun/test/fedora-rawhide-x86_64/00850682-libfm-qt/build.log.gz

**Comment by tsujan** [comment]
@agaida Can this be our problem?

**Comment by agaida** [comment]
Dunno right now. Never was bitten by this.

**Comment by david-geiger** [comment]
This come from "${REQUIRED_QT_VERSION}" who is not defined/set in the CMakefilesList.txt.

**Comment by agaida** [comment]
haha, seems i messed this one up :) 

Thanks for finding it and the patch
