### ISSUE TITLE
Recursive copy to smb shares is faulty

### ISSUE THREAD

**Issue by agaida** [lxqt/libfm-qt#385]
##### Expected Behavior

I should able to copy whole trees to a smb share

##### Current Behavior

A bug message comes up:
![](https://i.imgur.com/eQ3r1fW.png)
in this case the dir fixes will be created before the bug is thrown.

##### Possible Solution

fix it?

##### Steps to Reproduce (for bugs)

1. mount a smb share via pcmanfm  
2. try to copy a dir from a local machine to the share

##### Context
normal and everyday copy actions should just work.

##### System Information
debian sid / latest git

**Comment by tsujan** [comment]
I thought SMB problems were fixed. I vaguely remember someone described a similar problem but with V0.13.

**Comment by agaida** [comment]
i thought that too - but ..

And i'm more or less sure that i tested copying to smb when we fixed these things. (copied some of my local folders to my new NAS)

**Comment by agaida** [comment]
I might be wrong, but i have the vague feeling that something has been changed in gio/gvfs

**Comment by tsujan** [comment]
Tomorrow, I'll first test with sftp; then, will take a look at the code. Hopefully, the cause will reveal itself.

**Comment by tsujan** [comment]
I did the test just now: sftp recursive copy works without problem and I couldn't find an issue in the code (`filetransferjob.cpp`).

Is it possible that, when the dir `fixes` is created, it doesn't have right permissions?

**Comment by agaida** [comment]
it might be - but to be honest - i never noticed that bug, it was a conversation in IRC - and i could reproduce at the first attempt - i will try a different approach - mount the share by hand and test again

**Comment by tsujan** [comment]
> it might be

Can you make sure of that? The error is GLib's `G_IO_ERROR_NOT_SUPPORTED`.

**Comment by tsujan** [comment]
What about theses commands (with `gio`, if you have it):
```
gio mkdir DIR_INSIDE_SMB
gio copy LOCAL_FILE DIR_INSIDE_SMB
```
If they succeed, the bug is definitely in libfm-qt.

**Comment by agaida** [comment]
i have gio - you remember our discussion about a dependency on gvfs-bin or so?

ok, here we go:
```
% gio mount smb://idefix/music/                                                                        
Für den Speicherort music auf idefix wird ein Passwort benötigt
User [agaida]: 
Domain [WORKGROUP]: 
Password:
```
the mounted music share
```
Mount(0): music auf idefix -> smb://idefix/music/
  Type: GDaemonMount
  default_location=smb://idefix/music/
  themed icons:  [folder-remote]  [folder]  [folder-remote-symbolic]  [folder-symbolic]
  symbolic themed icons:  [folder-remote-symbolic]  [folder-symbolic]  [folder-remote]  [folder]
  can_unmount=1
  can_eject=0
  is_shadowed=0
```
Now gio is falling short - i had to guess the real path where the mount is located
```
% gio info smb://idefix/music
Anzeigename: music auf idefix
Name bearbeiten: /
Name: /
Typ: directory
Größe:  0
Adresse: smb://idefix/music/
Attribute:
  standard::type: 2
  standard::name: /
  standard::display-name: music auf idefix
  standard::edit-name: /
  standard::icon: folder-remote, folder-remote-symbolic
  standard::content-type: inode/directory
  standard::size: 0
  standard::allocated-size: 0
  standard::symbolic-icon: folder-remote-symbolic, folder-remote
  etag::value: 1554677386
  id::filesystem: smb-share:server=idefix,share=music
  access::can-trash: FALSE
  time::modified: 1554677386
  time::modified-usec: 0
  time::access: 1554677386
  time::access-usec: 0
  time::changed: 1554677386
  time::changed-usec: 0
  unix::device: 117081532
  unix::inode: 25

# translates to
% mount | grep gvfs
gvfsd-fuse on /run/user/1000/gvfs type fuse.gvfsd-fuse (rw,nosuid,nodev,relatime,user_id=1000,group_id=1000)

# voila
% ls /run/user/1000/gvfs/smb-share:server=idefix,share=music -l
insgesamt 760
drwx------ 1 agaida agaida      0 Mär 24  2018 '3 Doors Down'

% gio mkdir smb://idefix/music/2test
fine

% LANG=en_US.utf-8 gio copy Kvantum-0.10.6 smb://idefix/music/2test                                                                                                  :(
gio: file:///home/agaida/test/Kvantum-0.10.6: Can’t recursively copy directory
^^^ upps
```

**Comment by tsujan** [comment]
No, try to copy only one file, not a dir, into `smb://idefix/music/2test`.

**Comment by agaida** [comment]
one file works fine

**Comment by tsujan** [comment]
OK. I have a wild guess but I should really set up samba in my 2 Manjaro installations tomorrow. The last time, I didn't succeed but I hope it was because of firewall.

**Comment by agaida** [comment]
the culprit seems to be:
**cp -av foo bar**
cp: preserving permissions for ‘/run/user/1000/gvfs/smb-share:server=idefix,share=music/2test/Kvantum-0.10.6/themes/openbox/KvDarkRed/openbox-3/max.xbm’: Operation not supported
**cp -rv foo bar**
 'Kvantum-0.10.6/debian/upstream' -> '/run/user/1000/gvfs/smb-share:server=idefix,share=music/2test/Kvantum-0.10.6/debian/upstream'
'Kvantum-0.10.6/debian/upstream/metadata' -> '/run/user/1000/gvfs/smb-share:server=idefix,share=music/2test/Kvantum-0.10.6/debian/upstream/metadata'
'Kvantum-0.10.6/debian/watch' -> '/run/user/1000/gvfs/smb-share:server=idefix,share=music/2test/Kvantum-0.10.6/debian/watch
```
preserving permissions and/or attributes might be a not so good idea

**Comment by agaida** [comment]
only a gut feeling

**Comment by tsujan** [comment]
Preserving permissions was exactly my wild guess ;) It is preserved in the code. Anyhow, by setting up samba, I could see it first hand.

**Comment by agaida** [comment]
i see we think the same way again - cool

**Comment by agaida** [comment]
anyways - i'm not patient enough to setup a samba server again so i bought rockstor a year ago and am still happy with - ok, i mis-use this machine as a kind of terminal server via rdp - the LXQt version in CentOS should be more current.

**Comment by tsujan** [comment]
The problem is that, even if I set up samba, both ends will be Linux, so that the problem might not be visible to me.

Could you do a boring test? Change https://github.com/lxqt/libfm-qt/blob/4b18566d28702bf56a0e338bcee3038adc909442/src/core/filetransferjob.cpp#L96 to:
```c
int flags = G_FILE_COPY_ALL_METADATA | G_FILE_COPY_NOFOLLOW_SYMLINKS | G_FILE_COPY_TARGET_DEFAULT_PERMS;
```
and see what happens?

**Comment by agaida** [comment]
in my case it is linux on both ends - but yes, i can change and test

**Comment by tsujan** [comment]
> in my case it is linux on both ends

Oh, that's good :)

**Comment by agaida** [comment]
no - it changes nothing :(

**Comment by tsujan** [comment]
OK. Thanks! Let's see what will happens tomorrow. I need a deep sleep now :)

**Comment by agaida** [comment]
dito :) gn8

**Comment by tsujan** [comment]
OK, I couldn't sleep more than 90 minutes -- that's my curse: when something is unfinished, it occupies my mind during sleep. So, I woke up, set up samba (piece of cake -- firewall was the culprit before) and found the cause in a few minutes:

The code tries to set the "correct" directory permissions after creating the directory inside the function `FileTransferJob::makeDir()` but that's impossible with samba; hence "Operation not supported". Then, `makeDir()` returns `false` and everything is canceled. So straightforward!

Since samba may not be the only exception and because we can't rely on an exception list, I think the code should only try once to set permissions and, if unsuccessful, it should ignore the error and continue, trusting GLib for right permissions. I changed the code accordingly and recursive samba copy proceeded without problem.

**Comment by tsujan** [comment]
There's another thing unrelated to this but I remembered it during the discussion:

When `sudo cp` is used to copy a user (local) file to a root (local) directory, the permissions of the copied file changes to those of root, which is good. But with most file managers -- pcmanfm-qt included -- the permissions are preserved. That has been annoying to me for a long time, so that I never use a FM for such jobs. Am I alone in this?
