### ISSUE TITLE
missing licence header of test cases

### ISSUE THREAD

**Issue by damianatorrpm** [lxqt/libfm-qt#404]
The tests in sub-directory test/ are missing licence headers. 
It would be best practice to explicitly add them.

EDIT:
something is missing - bug report number 404

**Comment by damianatorrpm** [comment]
If it is desired I can add them in a PR but I am unsure as whom to write as author there.
As far as I see the commit history that would be PCMan.

Would there be any objections to do so?

**Comment by tsujan** [comment]
> Would there be any objections to do so?

No objection here.

> As far as I see the commit history that would be PCMan.

I think so too.

**Comment by agaida** [comment]
it is best practice

**Comment by PCMan** [comment]
Already merged. Thanks

Alf Gaida <notifications@github.com> 於 2019年4月19日 週五 上午3:28 寫道：
