### ISSUE TITLE
save dialog should change filename extension when different File Type is selected

### ISSUE THREAD

**Issue by wxl** [lxqt/libfm-qt#423]
Save dialogs have a File Type drop down and programs like Falkon have several default features. Upon being opened initially, one of them is selected and the appropriate extension given to the default filename. However, when changing the File Type, the extension in the filename does not change accordingly.

##### Expected Behavior
When selecting a different File Type, the filename updates with the appropriate extension.

##### Current Behavior
When selecting a different File Type, the filename does not update.

##### Possible Solution
I'm not suggesting that somehow we overwrite or modify the defaults or the options available in the File Types, but that where an application provides more than one option, selecting a different File Type will result in a change to the file name extension.

##### Steps to Reproduce (for bugs)
 1. Right click on page in Falkon 
 1. Click Save As 
 1. Note File Type is MIME Type Archive (*.mhtml) and extension of file name is .mhtml 
 1. Change File Type to HTML page, single (*.html) 

##### Context
See #421 for other improvements to the save dialog that led to this idea.

##### System Information
 * Distribution & Version: Lubuntu 19.10
 * Kernel: 5.0.0-13-generic
 * Qt Version: 5.12.2
 * libqtxdg Version: 3.3.1-0ubuntu2
 * lxqt-build-tools Version: 0.6.0-2ubuntu1
 * Package version: 0.14.1-0ubuntu2

**Comment by tsujan** [comment]
A nice feature to add. It may be not be as simple as the above description because the File Type combo may contain multiple extensions but I'll find a reasonable way.

**Comment by tsujan** [comment]
Update:
I was easier than I thought. The patches for this and https://github.com/lxqt/libfm-qt/issues/421 should be the same because they have common codes. Will test them more.
