### ISSUE TITLE
Possible bug

### ISSUE THREAD

**Issue by shlyakpavel** [lxqt/libfm-qt#445]
https://github.com/lxqt/libfm-qt/blob/2f3c1fefa03cfbe2ccd586f5defb9d2ecce667a9/src/core/gioptrs.h#L102-L103
The code above looks weird. Perhaps `err = nullptr;` was meant

**Comment by tsujan** [comment]
`err_ = nullptr;` should be removed. Would you do it?

**Comment by tsujan** [comment]
> Perhaps err = nullptr; was meant

No, that line should be removed.
