### ISSUE TITLE
[question] dialogs

### ISSUE THREAD

**Issue by damianatorrpm** [lxqt/libfm-qt#448]
The dialogs (app-chooser, file-dialog, file-props etc) have in my opinion not the best default sizes and could use UI overhaul (without loosing any functionality) of course.

While I think that some minor UI tweaks that improve usability would already help somewhat, 
I would like to ask if QtQuick based dialogs would be acceptable for libfm-qt

**Comment by tsujan** [comment]
> I would like to ask if QtQuick based dialogs would be acceptable for libfm-qt

No QML/QQC in LXQt -- only real widgets! I'm serious.
