### ISSUE TITLE
usr/share/applications should be trusted by default

### ISSUE THREAD

**Issue by agaida** [lxqt/libfm-qt#456]
##### Expected Behavior
If one browse to /usr/share/applications one should be able to double click and the application should open.

##### Current Behavior
Our popup for not trusted applications show up - second: i set all the desktop files in /u/s/a trusted - in that case the applications open as expected. The current behaviour don't make sense because of three reasons:
* /usr/share/applications is the default location for desktop files installed by package managers - first reason for default trust
* /usr/share is admin area - only root or root equiv can write into, package managers need this auth too
* We don't show the exclamation marks anymore - so the user have no clue that there is no trust 

##### Solution
we should remove the "Set trusted" in context menu too trust by default.

**Comment by tsujan** [comment]
I disagree. Dolphin doesn't trust them either. There's no reason to trust them because this is a file manager, not a menu.

**Comment by agaida** [comment]
tststs - test it

**Comment by agaida** [comment]
Dolphin does it wrong - the same files are "trusted" when running from the Menu :sunglasses:

**Comment by agaida** [comment]
How should a user know that he must trust the files? There is no exclamation mark ...
![](https://i.imgur.com/Kwk6nWr.png)

**Comment by tsujan** [comment]
> tststs - test it

Did, right now:

![dolphin](https://user-images.githubusercontent.com/981076/63217087-eb439800-c154-11e9-8e15-61e347fa4b5d.png)

> Dolphin does it wrong - the same files are "trusted" when running from the Menu

I answered that: this is a file manager, *not a menu*. The concept of "trust" doesn't have anything to do with menus (I vaguely remember you corrected a user's misconception with similar words).

**Comment by tsujan** [comment]
> How should a user know that he must trust the files?

Click on them and the prompt is shown if not trusted.

Moreover, the same is true for all executables. The emblem is just for desktop entries because ordinary users may work with them.

**Comment by agaida** [comment]
erm - we have a Application Menu in our file manager - same files, different behaviour - not wise - people might want to buy our drugs :D

**Comment by tsujan** [comment]
> we have a Application Menu in our file manager

That's very different -- a sort of (weird) bonus. And even so, there's no emblem there now.

**Comment by agaida** [comment]
the problem is that the place /usr/share/applications is trusted by default

**Comment by tsujan** [comment]
It is NOT. I (as a users) don't want a desktop file to be executed *in my file manager* without prompt. After all, I like to open them with a text editor when I use a file manager. If someone wants them to be executed without prompt, they could trust them.

**Comment by agaida** [comment]
it is - you do this on a daily base - and if we don't trust them they must have the exclamation mark ...

Consistent behaviour. And i talk only about /usr/share/applications and subdirectories - all other locations are _not_ trusted by default

**Comment by tsujan** [comment]
> and if we don't trust them they must have the exclamation mark

No. We don't want to add that emblem everywhere. Otherwise, they should be added to most files in /usr/bin. Dolphin is a good example to follow. There's a lot of experience and experiment behind it.

Emblems are only for the user's home. They shouldn't be added anywhere else. But the concept of trust is valid everywhere. Again, I like how Dolphin handles it.

**Comment by agaida** [comment]
And again - it make sense in every other location - it is plain false in /usr/share/applications

**Comment by tsujan** [comment]
> it is plain false in /usr/share/applications

Again: As a user, I have a right not to want any executable to be run without prompt in my file manager *by default*; its locations isn't important. Otherwise, the file manager would have a bad design, exactly because it's a file manager, not a menu.

**Comment by agaida** [comment]
ok - your opinion - pcmanfm, nautilus, dolphin follow your opinion, thunar and nemo rightfully not

**Comment by agaida** [comment]
i have a problem with this kind of view - maybe a picture make it better understandable - and so far is nautilus the only file manager in my short test who do it right.

![](https://i.imgur.com/nERv9yM.png)

In both wrong examples the files in /usr/share/applications are displayed as starters - only nautilus show them as the simple files they are. Glad that we talk about it - i really like the nautilus behaviour, i don't know how many times i polished my swearword knowledge when i run into this.

**Comment by tsujan** [comment]
> ok - your opinion - pcmanfm, nautilus, dolphin follow your opinion

The only time I liked Nautilus ;)

As for your screenshot, I didn't understand how that ugly Nautilus with those ugly icons could be good ;) I think you mean only one file: "AnyDesk"? What is it? What's its content (for me to see it first hand)?

**Comment by agaida** [comment]
the ugly file in nautilus is the file "nautilus.desktop" in /usr/share/applications - no default  app for desktop files, so a generic icon ...

**Comment by tsujan** [comment]
> Edit: and nautilus shows me rightfully the full name "anydesk.desktop" instead of "Anydesk" or "foo" in my example

Don't remember this? Preferences → Display → Always show full file names

**Comment by agaida** [comment]
Plain no :D

**Comment by tsujan** [comment]
OK :) It seems I'm not the only one dying for a little sleep ;)

**Comment by agaida** [comment]
But now that you mention it - it is fucking ugly
![](https://i.imgur.com/psHHHZJ.png)

**Comment by tsujan** [comment]
> it is fucking ugly

Agree. But it's an option added because.... I don't remember why but there was a good reason.

**Comment by agaida** [comment]
it was the app1.desktop app2.desktop thing - and it make sense when the default representation come from inside of a file

**Comment by agaida** [comment]
or in other words:
On Desktop - interpret the desktop file
On pcmanfm-qt/Applications - interpret the desktop file
All other places: Please show them as files.

**Comment by tsujan** [comment]
pcmanfm-qt has both options. IMO, the default is sane.

However, we could have made an exception for files on desktop *when the full file name was shown*. Actually, it came to my mind but I also thought it might not be a good idea to exclude Desktop with that option. I don't know.... If you think it's important, I'll implement it later.

**Comment by agaida** [comment]
to be clear about - you mention rightfully that pcmanfm-qt is a file manager - and should behave as one.
You don't like the ugly nautilus representation of the dir - understandable. So let the "Show Full Name" the default in the filesystem - only the Desktop and Applications should behave different per default

**Comment by agaida** [comment]
This would solve the "Trust" problem too automagically, because the users see the plain files, nicely decorated. And files should not be directly executable from a file manager :D

**Comment by tsujan** [comment]
Opened https://github.com/lxqt/pcmanfm-qt/issues/996

**Comment by tsujan** [comment]
Let's not lose any option or change any default. pcmanfm-qt's defaults are good, IMO. We could change this or that behavior instead, so that opposite viewpoints could actualize by changing this or that option.

**Comment by tsujan** [comment]
I think this isn't needed anymore; I even changed the default as you told. Superseded by https://github.com/lxqt/pcmanfm-qt/issues/996
