### ISSUE TITLE
Possible unregistered build-time dependency: qtbase5-private-dev

### ISSUE THREAD

**Issue by niacdoial** [lxqt/libfm-qt#464]
When trying to build libfm-qt on my own (commit 7231722fd7696867bab2ca228a451746161a8bac), CMake did not seem to know that I needed qtbase5-private-dev for the compilation.

##### Expected Behavior

After succeding the CMake pre-build (configure/generate, output set to unix Makefiles) with no warnings,
the make command should be able to also succeed

##### Current Behavior

After succeeding the CMake pre-build, the make command fails, due to the missing include file `<private/qdnd_p.h>` (which is said to be part of the private part of QT5 on a comment on the same line of code)

##### Possible Solution

This header, according to apt-file, is part of the package qtbase5-private-dev
A possible solution is to add this dependency to the CMake pre-build config files

##### Steps to Reproduce (for bugs)

1. get the source code for libfm-qt on a "brand new" (no QT-related '-dev' packages) system
2. try to pre-build it with CMake, fail to do so, and install the missing dependencies that appear in the CMake error log
3. Repeat step 2 untill CMake succeeds
4. try to build libfm-qt with make

##### System Information

* Distribution & Version: ...Ubuntu 18.04 LTS
* Kernel: 4.15.0-1050
* Qt Version: 5.9.5+dfsg-0ubuntu2.3
* libqtxdg Version: 3.1.0-5build2
* lxqt-build-tools Version: 0.6.0-2ubuntu1 (from the Ubuntu 19.04 repository)
* Package version: [upstream source code, commit 7231722fd7696867bab2ca228a451746161a8bac]

**Comment by agaida** [comment]
Downstream bug - not really of any interest upstream

**Comment by agaida** [comment]
And again: The way to build things for Ubuntu is: Use the distribution tools and don't use cmake directly:
* it is no fun to use cmake
* it will wreck your system if no package manager is used
* it is simply wast of time

**Comment by tsujan** [comment]
@agaida explained it well in Debian terms. In more general terms:

`qtbase5-private-dev` is a distro-specific thing. Qt is Qt; whether a distro splits it into several packages isn't a cmake problem to solve.

**Comment by tsujan** [comment]
More importantly, when a source that uses a private header is compiled and packaged against Qt 5.X, the compilation/package won't be valid for Qt 5.X+1. Again, not a cmake problem to solve.

**Comment by niacdoial** [comment]
At this point I am more than three days late, even though I read your answers in the hour...
anyway thanks for telling me this!
(I hope this passage doesn't reopen the issue...)
