### ISSUE TITLE
Plugin for copy system

### ISSUE THREAD

**Issue by alphaonex86** [lxqt/libfm-qt#499]
Hi,

It's possible to have plugin system to send copy/move to external software?
Related with https://github.com/lxqt/libfm-qt/pull/498

Cheers,

**Comment by tsujan** [comment]
As an extension of a clean plugin support yes -- but you need to add the plugin support first, perhaps to pcmanfm-qt (see https://github.com/lxqt/pcmanfm-qt/issues/40); it would be welcome.

Inside the main code of libfm-qt, no!
