### ISSUE TITLE
Horizontal wheel scrolling doesn't work in compact mode with Qt 5.14.0

### ISSUE THREAD

**Issue by tsujan** [lxqt/libfm-qt#500]
In short, that's because an old bug is fixed in Qt 5.14.0. I'll make a PR.

But, ironically, a new bug is introduced by Qt 5.14.0. We shouldn't do anything about it, IMO; it isn't very important and happens in all apps: for horizontal wheel scrolling with mouse cursor over the horizontal scrollbar, `Alt` should be pressed. Previously, in all versions of Qt, `Alt` wasn't needed when the cursor was over the scrollbar.

**Comment by Chiitoo** [comment]
See also: https://bugreports.qt.io/browse/QTBUG-81007

**Comment by tsujan** [comment]
@Chiitoo Thanks!

No need to add a workaround for LXQt. But I added workarounds to FeatherPad and FeatherNotes because it was a serious issue there.
