### ISSUE TITLE
crash [master] | heavy ram usage [0.14.1]

### ISSUE THREAD

**Issue by damianatorrpm** [lxqt/libfm-qt#509]
I tested the following:
touch {0..10000} #ceate 100.000 files in a directory

1. navigate to this directory but change directory before it finishes loading.
2. ram usage increases as Fm:Folder gather FileInfo's
3. repeat.
4. The ram usage increase stops at some point but ram usage is higher than if
 folder change operation was never cancelled. I think this is because Fm::FileInfo are created and destroyed instead of cached to some extend.

Ram usage if folder change is never cancelled ~280 MB with PCman (and others)
If done continuously cancelling the folder change ~900 MB

Maybe it should cache a non-finished-loading folder as well like the loaded folder ?

The ram usage on folder change behavior was tested with 0.14.1 with current master
pcman-fm crashed on cancelling the folder change and than again opening that folder.
In master non-pcman libfm program does not crash but still heavy ram usage.

**Comment by tsujan** [comment]
1. RAM usage is controlled by Linux. It depends on many factors. libfm-qt/pcmanfm-qt has no memory leak as far as I tested with valgrind. With my 16G RAM, if I heavily use pcmanfm-qt for 2 days, its RAM usage may increase to 280 MiB but it stops there and sometimes decreases afterwards. Other Qt apps show similar behaviors.

2. For any crash, please open a report, describe the way of reproducing it and add a backtrace.

**Comment by agaida** [comment]
imho it is one of the miracles Qt does right - if RAM is available, fucking use it - an it seems to use it, so everything is all right - we should force it

**Comment by tsujan** [comment]
Yes, something like that. It isn't limited to Qt though; I see it also with non-Qt apps sometimes. But I can see it in Qt apps easily: I open a huge doc with FeatherPad, then close the tab and open a small file. The memory usage is much more than when I only open that small file but it doesn't increase so much when I open the huge file again.

**Comment by damianatorrpm** [comment]
I do think that this is a bug though. I am not saying that I am not willing to write a patch file for that,
dismissing the validity of the bug is technically wrong IMHO
It is good to have a bug tracker so stuff does not get forgotten somewhere locally.

https://sayingimages.com/wp-content/uploads/be-ever-in-your-favour-may-the-force-be-with-you-meme.jpg

**Comment by tsujan** [comment]
> dismissing the validity of the bug is technically wrong IMHO

It isn't about dismissing anything but having a real bug report. Crash needs its own report (see above). Memory leak isn't something you could discover only by comparing RAM usages.

**Comment by damianatorrpm** [comment]
I have been comparing some of the design of libfm-qt and libpeony-qt (another gio / qt based file manager).
https://github.com/ukui/peony
https://www.omgubuntu.co.uk/2020/02/ubuntu-kylin-ukui-desktop-qt

Anyhow, I've found this comment in src/peony-application.cpp that I wanted to share with you
```
        //BUG: it is not safe loading a new uri when
        //a directory is loading. enve thoug the file enumemeration
        //is cancelled and, the async method from GFileEnumerator
        //might still run in thread and return.
        //This cause program went crash.
```

**Comment by tsujan** [comment]
> Anyhow, I've found this comment...

Each code comment makes sense in the context of its corresponding code.

We ignore the result of a cancelled dir list job at the beginning of `Folder::onDirListFinished()`. The rest is done by GLib.

That being said, as mentioned above, if you've encountered a crash with the latest git, please open an issue, describe the way of reproducing it if it isn't random (if it's random, explain under which circumstances it's most probable), and, most importantly, **attach a backtrace**.
