### ISSUE TITLE
Fm::FilePath drag 'n drop & breadCrumbs

### ISSUE THREAD

**Issue by damianatorrpm** [lxqt/libfm-qt#513]
EDIT: Doing further testing

Below you will find (a long read) an explanation and possible solution
of 3 related issues in the way libfm-qt / glib exposes Fm::FilePath's
related to breadCrumbs and drag 'n drop for ***any non file scheme*** item

Also at the bottom the notes may provide something for other issues.

The possible solution would need to be adapted to the way
PCmanFM handles breadCrumbs / drag and drop.
(I guess a Qt Widgets implementation as widgets are used in many parts of libfm-qt)

I share this in the hope you find this useful!

In the first example I used google drive as it shows the breadCrumb issue: 

> Although this is a general issue with missing glib functionality 
> - g_file_get_diplay_path() missing
> - g_file_get_local_uri() / g_file_get_escaped_path() missing
      uri escapes special charachters somehow path does not

How PCmanFM works:

> location_bar 		=> text bar => shows the scrambled path` google-drive://damianatorrpm@gmail.com/1M8aIvIGsjJMw2Z9dHPO3CsaauOMIDWCS`
> 
> bradcrumb_bar 		=> button list => shows the scrambled path for each entry  
> 
> copy to clipboard 	=> it uses uri 
> 			   text/uri-list no information here regarding copy/cut but libfm-qt foldermodel has isCut
> 			   cut/paste doesnt not work with other file managers (I think that is OK though!)			
> 			   `google-drive://damianatorrpm@gmail.com/0B_wtRVB2Z4pvd0ptcWMyYXkxUDg/0B_wtRVB2Z4pvYmlnX2Vobm9kZmc`
> 
> drag and drop     	=> it uses uri 
> 			   application (no glib uri support) accepting drop:
> 			   Error loading google-drive://damianatorrpm@gmail.com/1M8aIvIGsjJMw2Z9dHPO3CsaauOMIDWCS
>  or any other non-local uri scheme

How nautilus works:

> location_bar      => text bar => shows the scrambled path` google-drive://damianatorrpm@gmail.com/1M8aIvIGsjJMw2Z9dHPO3CsaauOMIDWCS`
> 
> bradcrumb_bar     => button list => shows the correct display name for each part of the path 
> 
> copy to clipboard => it uses the gfile_get_uri for each selected item e.g probably with the rationale 
> 		     that this is only used for nautilus internal copy/move type of actions
> 			//nautilus-clipboard is the new nautilus only clipboard data format, not replacing the other gnome clipboard format
> 			cut/paste doesnt not work with other file managers they don't implement that (I think that is OK though!)
> 			```
> x-special/nautilus-clipboard 
> 			copy
> 			google-drive://damianatorrpm@gmail.com/1GEOasKTjchZnSQuY6IAZzSHYfR0L3KIF/1v4_eLfGyUUbj50ca2qZt_JZ3BFkA-Pdw
> ```
> 
> drag and drop     => it uses the localpath (GVFS FUSE mapped) and (probably) uses the path list generated 
>                      with each part of the path using its display name as there is no function g_file_get_display_path
> 

to gather the text/uri-list mimeData I tried:

=> QString("file://") + Fm::FilePath::localPath() for each selected item 
(and applications that receive the file complain)
- returns an invalid path for local file: 
    for file names containing some special charaters
`    &**  ()**(&^ &*^ &^^%^ !@^ @#&*(* ()#*)( ) +_) .file 
`    does not work 

    `&**  ()**(&^ &*^ &^^%^ !@^ @#&*(* ()#*)( ) +_) .file `
    works for tested applications if the file is local and uri is used
    and as such applications that do not support glib uri they still understand
    file:// protocal localpath(g_file_get_path) and uri(g_file_get_uri) report different
    filenames as uri escapes some charachters

- returns an invalid path for google-drive fuse mapped files
  apllications do not accept pathname:
 ` file:///run/user/1000/gvfs/google-drive:host=gmail.com,user=damianatorrpm/1CAmmoa3NZOmAVBD_hoN3BRyTCfLQ7tzP/3dfsr3anotherHash23150`
  applications do accept pathname:
` file:///run/user/1000/gvfs/google-drive:host=gmail.com,user=damianatorrpm/DISPLAY_NAME_OF_DIR/DISPLAY_NAME_OF_FILE`

I tested DND with the following applications
> =>Clementine probably supporst only paths or file:///path/to/file 
> =>VLC probably supporst only paths or file:///path/to/file 
> =>Gedit supports only uris not paths

Current Drag and Drop behaviour:
> nautilus - dragging files from any location into any application I tested works flawlessly 
> PCmanFM - dragging files works only for applications that support glib style uris
                       which works as long as it is the local file scheme

My implementation does the following, the code below is edited to be more generic,
in case you want to use it. Variable names are different.

to gather the list for the breadCrumbBar and for the mimeData
a similar approach would fix those in PCmanFM:
(fix the invalid local path name and the local fuse mapped gdrive path name
  and google drive breadCrumbs)

EDIT: one part for below to work correctly is missing will update
```c++
    QString m_complete_local_path = g_file_get_path(pathToFileChar);
    m_complete_local_path.remove("file://"); //or uriScheme for breadCrumb
    const QStringList& completePathStringList = m_complete_local_path.split("/");
    QString m_previous_parts;
    QString m_complete_mapped_local_path;

    for (int iter = completePathStringList.count(); iter-- > 0;) {
    const QString& partOfPath         = completePathStringList.at(iter);
    const QByteArray& partOfPathArray = m_previous_parts.toUtf8() + partOfPath.toUtf8();
    const char* partOfPathChar        = partOfPathArray.constData();
    
    g_autoptr(GFile) m_gfile          = g_file_new_for_uri(partOfPathChar);
    GFileInfo* m_gfileInfo            = g_file_query_info (m_gfile,
                                                           "standard::copy-name",
                                                           G_FILE_QUERY_INFO_NONE,
                                                           nullptr,
                                                           nullptr);
    
    const QString& m_mapped_part      = g_file_info_get_attribute_as_string (m_gfileInfo,
                                                                             G_FILE_ATTRIBUTE_STANDARD_COPY_NAME);
    m_complete_mapped_local_path      += m_mapped_part 
            if (iter != 0)                    m_complete_mapped_local_path + "/";
    else                              break;
    m_previous_parts                  += m_finalBreadCrumb + "/" ;
    
    g_object_unref(m_gfileInfo);
}
m_complete_mapped_local_path.prepend("file://") //or uriScheme for breadCrumb
```

A few other notes unrelated to this bug but maybe relevant for other bugs, 
will test the latter more extensively (maybe for recent:// interesting as well):

I have not tested if this affects lxqt (or in what distribution) or if this is still an actual issue:
gvfs-fuse not starting correctly in in non gnome-session managed desktop environments

> https://gitlab.gnome.org/GNOME/gvfs/issues/393

> https://developer.gnome.org/gio/stable/running-gio-apps.html
> GIO_USE_FILE_MONITOR.  This variable can be set to the name of a GFileMonitor implementation to override the default for debugging purposes. The GFileMonitor implementation for local files that is included in GIO on Linux has the name "inotify", others that are built are built as modules (depending on the platform) are called "fam" and "fen". The special value help can be used to print a list of available implementations to standard output.

> https://bugzilla.redhat.com/show_bug.cgi?id=1367175
> "FAM (gamin) is currently used for monitoring NFS filesystems,"

**Comment by tsujan** [comment]
@damianatorrpm 
Frankly, I didn't understand *anything* after reading this page quickly. Whether I'm a bad reader or you're a bad writer can be a relevant question (I think I'm a good reader ;) ). Whenever I find the time, I'll read it again, hoping that I might find another good idea of yours in it.
