### ISSUE TITLE
Drag and drop behavior

### ISSUE THREAD

**Issue by damianatorrpm** [lxqt/libfm-qt#514]
I compared the behavior of three file managers regarding drag and drop:

1. PCmanFM sends a glib uri list (including glib-scheme:///)
2. Nautilus sends a fully encoded local path (escaped characters)
3. File Manager 3 now sends a fully encoded local path + workaround for google drive
   so applications that receive the drop show display name instead of real name.

 sending a glib uri list (including glib-scheme:///) is not good for drag and drop
as it expects applications to support glib uris. Important is that not the localPath()
can be used as is, but the localPath would need to be FullyEncoded.

```
             encodedUrl = encodedUrl.fromLocalFile(m_complete_mapped_local_path);
            files << encodedUrl.toEncoded(QUrl::FullyEncoded);
```

I see that this is done in FolderModel which is part of libfm-qt the mimeData from there is not so well usable in QML and has no scheme specific workarounds but I will come up with a proposed request for FolderModel::mimeData too

**Comment by tsujan** [comment]
I don't understand the problem. I drag and drop a file into FeatherPad — or any app that doesn't depend on GLib — and it'll be opened. You need to be more specific here.

**Comment by tsujan** [comment]
Superseded by https://github.com/lxqt/libfm-qt/issues/515

@damianatorrpm Please use the template to report a bug/feature request! I had to decipher this report. For a report that doesn't waste time, see https://github.com/lxqt/libfm-qt/issues/515
