### ISSUE TITLE
LXQt File Dialog: Better tab order

### ISSUE THREAD

**Issue by tsujan** [lxqt/libfm-qt#557]
##### Expected Behavior

If the main view is focused, the name entry will get focus by pressing the tab key once.
##### Current Behavior

When the main view is focused, the tab key should be pressed 3 times for the name entry to get focus.
##### Possible Solution

Will make a PR.
##### System Information

Latest git LXQt

**Comment by ralf3u** [comment]
to tsujan: you wrote in: https://github.com/lxqt/screengrab/issues/213
" GTK file dialog needs 4 tabs. LXQt file dialog (ours) needs 3 tabs..."

In Lubuntu 20.04 in ScreenGrab it is 3 or 4 tabs, and that depends in which file I'm:
if I'm in the home-file then it is 3 tabs
if I'm in the image-file then it is 4 tabs
and that without leaving the "Save As..."-window
I think that I'm using the LXQt file dialog.

(By the way: only the title bar and the Cancel-button are translated in German; everything else is in English)

**Comment by tsujan** [comment]
@ralf3u 
It doesn't matter now (it's 3 or 4 depending on some other factors). The PR is made and it'll implement the desired behavior when merged: https://github.com/lxqt/libfm-qt/pull/558

FYI:
The reason why it wasn't implemented sooner was that a Qt function, which should do it in theory, is unreliable. The patch is like a workaround.

**Comment by tsujan** [comment]
> By the way: only the title bar and the Cancel-button are translated in German; everything else is in English

Maybe because Lubuntu 20.04's LXQt is old. But a German translator should check the master branch to see if there is a problem or, simply, the strings aren't translated yet.

**Comment by ralf3u** [comment]
to tsujan:
Excuse me, if I ask this here, but in some of my created issues you wrote that I should use the new version of LXQt.
Ok, but I don't know how to upgrade LXQt in Lubuntu 20.04. I searched on internet, but I could not find a description.
Do you have a link where it is explained in detail how I can upgrade? (I'm a beginner in installation)
Or is it too difficult? Thanks in advance.

**Comment by tsujan** [comment]
> you wrote that I should use the new version of LXQt... Do you have a link where it is explained in detail how I can upgrade?

Although I dislike long comments, I don't have a short answer to your question either ;) Hence this boring comment:

First, I didn't mean that you *should* use the latest LXQt but, if you want the latest stable features/fixes, you'll need the latest release. Also, the latest release is needed for any kind of contribution, like valid bug reports or feature requests.

Second, what I do NOT recommend at all is installing from LXQt sources directly by compiling and using `sudo make install`.

Now, Linux distros can be divided into rolling and non-rolling. With non-rolling distros like Ubuntu, Fedora,..., you have to wait six months for major updates and, even in that time, there's no guarantee that you'll have the latest stable releases of all apps/libraries. With rolling distros like Debian Testing, Arch, Manjaro Testing, OpenSUSE Tumbleweed,..., you usually have the latest stable versions. (Warning: unfortunately, Debian's LXQt isn't up-to-date due to a temporary problem but "temporary" can mean a long time in the Debian world.)

Therefore, if you want to stay with Lubuntu, you have two or three options: (1) You can accept that the LXQt version Lubuntu gives you isn't up-to-date most of the time; (2) You can upgrade to the unstable Ubuntu but I don't recommend that because your system may become really unstable or even broken; or (3) you can learn how to make deb packages (= installable packages of Debian-based distros like Ubuntu) out of the latest sources for your personal use.

The bad news is that making deb packages isn't easy to learn and you might break your system if you make "bad" deb packages. The good news is that, *once you learn it*, it'll become a piece of cake; but that requires a considerable amount of experience.

Your other option is switching a user-friendly rolling distro. The best example that comes to my mind is Manjaro Testing. Here too, there are bad news and good news: You'll need to change your habits because Manjaro is based on Arch, which is very different from Debian (the foundation of Ubuntu); but you'll get the latest software continuously while having a stable and fast system. If you want to try another distro, I recommend you keep your Lubuntu and use VirtualBox or another partition/computer for trying.
