### ISSUE TITLE
LXQt file dialog isn't localized in Qt apps that don't depend on libfm-qt

### ISSUE THREAD

**Issue by tsujan** [lxqt/libfm-qt#596]
##### Expected Behavior

LXQt file dialog should be localized everywhere.
##### Current Behavior

LXQt file dialog is localized only in apps that are based on libfm-qt.
##### Possible Solution

The cause is simple: we don't load libfm-qt translations in `libfm-qt → filedialoghelper.cpp → createFileDialogHelper()`. The solution is as simple as the cause. I'll make a PR soon. 
##### Steps to Reproduce (for bugs)

1. Open FeatherPad (or Falkon/Kate/...) with `LANGUAGE=it fpad`.
2. Open a file dialog from FeatherPad.

It isn't in Italian. If you do the same thing with lximage-qt, the file dialog will be in Italian.

##### Context

@mkkDr2010 and @stefonarch found the bug at https://github.com/lxqt/pcmanfm-qt/issues/1254.
##### System Information

* Latest git LXQt

**Comment by mkkDr2010** [comment]
Yes, it works perfectly! Now I notice no problems with translation. Thanks!

**Comment by tsujan** [comment]
@mkkDr2010, thanks for testing the PR! Your test was needed and is appreciated.

@stefonarch, it seems that only you don't confirm the fix. It works for @mkkDr2010, @ito32bit and me. I prefer to wait until you find the cause. There's no hurry, of course.

**Comment by stefonarch** [comment]
I've really no clue what remains to check more here, so feel free to  merge.

**Comment by tsujan** [comment]
> ... feel free to merge.

A week or so later. The bug has existed for 3 years; one more week doesn't count ;)

**Comment by stefonarch** [comment]
I'd be happy to find the thing...

**Comment by tsujan** [comment]
> I'd be happy to find the thing...

I know you're very busy. No need to spend time on this. If it's found, so good; if not, no disaster will happen.
