### ISSUE TITLE
Smooth scrolling shouldn't be used for touchpads in Icon and Thumbnail views

### ISSUE THREAD

**Issue by leschalu** [lxqt/libfm-qt#611]
##### Expected Behavior
Immediate scrolling with touchpad(like using scrollbar).

##### Current Behavior
Scrolling with touchpad works like with mouse wheel(update after input event) which isn't responsive.

##### Possible Solution
In Detailed List it scrolls well.

##### Details
version - 0.16.0
driver - libinput

**Comment by tsujan** [comment]
> Smooth scrolling shouldn't be used for touchpads

There's no specific code for touchpad in libfm-qt.

Also, try Dolphin or any app with smooth scrolling.

> Immediate scrolling with touchpad

Wherever there's a smooth scrolling, there's a delay. It's just 20 milliseconds in libfm-qt. If you see a longer delay, your touchpad or its setting may have a problem.
