### ISSUE TITLE
Help needed: A problem with maximum file size for thumbnail creation

### ISSUE THREAD

**Issue by tsujan** [lxqt/libfm-qt#642]
libfm-qt's built-in image thumbnailer allocates an amount of memory as large as the file size to create its thumbnail. Therefore, huge images can cause trouble and that's why we have a max. size limitation (which is enabled by https://github.com/lxqt/libfm-qt/commit/73e73354b10fe9d757a498ca210c46f3cff7e52d -- previously, it had no effect).

On the other hand, external video thumbnailers don't have that limitation and can easily make thumbnails of videos as big as 1-2 GiB.

I set the limit for *all* thumbnails in https://github.com/lxqt/libfm-qt/commit/73e73354b10fe9d757a498ca210c46f3cff7e52d. Now, I think that may not be a good idea and it may be better to set the limit only on the built-in thumbnailer.

However, other file managers, like Dolphin, set a limit on *all* thumbnailers.

I don't know what to do. Should I keep the current git behavior (= the limit is for all thumbnailers)? Or should the limit be applied only on the built-in image thumbnailer (the text in pcmanfm-qt's Preferences can be changed to reflect that)?

The advantage of the first approach is self-consistency. Its disadvantage is that, if the user sets the limit to 1 GiB to cover videos, the same limit will be considered for 1-GiB images (are there any?) and 1 GiB of memory will be temporarily allocated for each.

Ides and suggestions would be appreciated.

**Comment by stefonarch** [comment]
Actual behaviour is not bad, I have limited it to 5mb  but can see videos thumbnails (ffmegthumbnailer?) with no issues.
So just make the text more explicit, excluding videos/externel thumbnailer? Are there others than ffmegthumbnailer?

**Comment by tsujan** [comment]
>  I have limited it to 5mb but can see videos thumbnails (ffmegthumbnailer?) with no issues.

That's because your video thumbnails were already created. If you see a new video > 5 MiB, it won't have a thumbnail.

> Are there others than ffmegthumbnailer?

You can have any kind of thumbnailer. I have one for PDF by using `graphicsmagick` and another one for Djvu.

I think distinguishing between the built-in and external thumbnailers is the best solution:

![two_limits](https://user-images.githubusercontent.com/981076/109811713-72296a00-7c40-11eb-9212-c233a40b5fab.png)

The second limit is for external thumbnailers and is disabled by default.

**Comment by tsujan** [comment]
Everything should be OK and backward-compatible after https://github.com/lxqt/libfm-qt/pull/644 and https://github.com/lxqt/pcmanfm-qt/pull/1328 :)

**Comment by stefonarch** [comment]
Works fine, but after setting a limit for the external thumbnailer going back to "no limit" is hard, -1 has to be hinted somewhere.

A tooltip for both "internal" and "external thumbnailer"?

**Comment by tsujan** [comment]
So fast! Thanks for testing!

> but after setting a limit for the external thumbnailer going back to "no limit" is hard, -1 has to be hinted somewhere.

-1 isn't shown to the user. He/she only sees "No limit".

Those who edit config files manually can set any negative number there (and they should always know what they're doing -- manual editing of config files requires extra knowledge).

> A tooltip for both "internal" and "external thumbnailer"?

I have no problem with tooltips. What do you suggest?

**Comment by stefonarch** [comment]
I didn't scroll all of it, I see "no limit is on the top, so no issue here. Inserting -1 works and will be replaced with the text.
> I have no problem with tooltips. What do you suggest?

Axplanation which file formats are handled by the internal thumbnailer, something about videos for the external?

**Comment by tsujan** [comment]
Oh, now I understand: You inserted -1 by editing, not by going below zero. I'll add -1 to the tooltip.

> An information which file formats are handled by the internal thumbnailer, something about videos for the external?

Good idea. Will add two tooltips to the PR.

**Comment by tsujan** [comment]
Added tooltips.

**Comment by stefonarch** [comment]
Looks perfect.
