### ISSUE TITLE
Distinguish between local and non-local files with thumbnails

### ISSUE THREAD

**Issue by tsujan** [lxqt/libfm-qt#643]
libfm-qt has an option to make thumbnails only for local files but that option has no effect for now (pcmanfm-qt inherits it in its Preferences dialog).

**Comment by stefonarch** [comment]
It works here with samba,  showing or not thumbnails on the other PC following setting in PCMan, maybe I miss something.

**Comment by tsujan** [comment]
@stefonarch, the code does absolutely nothing.

**Comment by tsujan** [comment]
Here, the problem is distinguishing between local and remote files. A native file may be remote (like a file in Google drive, mounted locally by `rclone`) and a non-native file can be local (like `trash:///`).

I tested by adding GLib's `G_FILE_ATTRIBUTE_FILESYSTEM_REMOTE` to libfm-qt (in 2 ways). It worked with trash (= local), smb (= remote) and sftp (= remote) but not with Google drive (should be remote but is considered local) and, probably, similar cases.

There's another GLib's attribute `G_FILE_ATTRIBUTE_FILESYSTEM_USE_PREVIEW` but it's mysterious to me and I didn't find it in the codes of well-known GTK file managers.

**Comment by tsujan** [comment]
I thinks the safest way of giving sense to that option is tolerantly considering "local" as "native". There is a good reason: most external thumbnailers — if not all — only work with native paths and, for example, can't make thumbnails inside `trash:///` or `recent:///` (while the built-in thumbnailer can). In this way, we'll have a more self-consistent thumbnail handling.

**Comment by tsujan** [comment]
After 3 years, I didn't find a way better than using what GLib proposed, namely, `G_FILE_ATTRIBUTE_FILESYSTEM_REMOTE`: https://github.com/lxqt/libfm-qt/pull/1004. It might be useful later, with other operations that we don't want to do with remote files (nothing for now).

**Comment by stefonarch** [comment]
I tested with ftp, looks working. Indeed toggling the option doesn't change anything.

**Comment by tsujan** [comment]
> toggling the option doesn't change anything.

It isn't supposed to reload anything (if you mean that). Either the view should be reloaded or the directory should be changed after toggling the option.

**Comment by stefonarch** [comment]
I meant remote thumbnails were always generated, with or without setting a hook at that option.

**Comment by tsujan** [comment]
Oh, you mean before the patch. Yes, remote internal thumbnails were always made.

**Comment by tsujan** [comment]
My approach failed (→ https://github.com/lxqt/libfm-qt/pull/1004#issuecomment-2283591234).

Since most parts of libfm-qt's code are optimized by using asynchronous info queries, a synchronous querying of filesystem info is a bad idea, while enabling of the setting about local-only thumbnails doesn't seem achievable asynchronously.
