### ISSUE TITLE
thumbnails are blurry with QT_SCALE_FACTOR<>1

### ISSUE THREAD

**Issue by bosim** [lxqt/libfm-qt#655]
##### Expected Behavior

Expect thumbnails are scaled properly

##### Current Behavior

Thumbnails are blurry, both using pcman-fm and lximage-qt so assume problems is in libfm-qt.

##### Possible Solution

No idea, have not looked into the code.

##### Steps to Reproduce (for bugs)

1. Run with e.g. `QT_SCALE_FACTOR=1.5`
2. Open a folder with images in pcmanfm-qt
3. See the thumbnails are blurry
4. 

##### System Information

* Distribution & Version: Debian 11 (bullseye)
* Kernel: 5.10
* Qt Version: 5.15.2
* libqtxdg Version: 3.6.0
* lxqt-build-tools Version: 
* Package version: 0.16

**Comment by tsujan** [comment]
Thanks for the report!

It isn't limited to lximage-qt but can be seen all apps that use libfm-qt.

I'll try to fix it in lbfm-qt before 0.17 but bigger thumbnails will mean more resource usage.

**Comment by tsujan** [comment]
Oops! Having seen your other report (https://github.com/lxqt/lximage-qt/issues/402), I thought you opened this one for lximage-qt. My bad! Its place is correct.

**Comment by tsujan** [comment]
The fix is here: https://github.com/lxqt/libfm-qt/pull/656. Tested it with videos, wallpapers and scale factors of 2 and 1.5.
