### ISSUE TITLE
Inconsistent Device Usage in File Properties Dialog

### ISSUE THREAD

**Issue by tsujan** [lxqt/libfm-qt#696]
##### Expected Behavior

The Device Usage shown by the progress-bar of the File Properties dialog on right clicking *an empty space* inside a `tmpfs` directory should be consistent with what `df -h` shows.
##### Current Behavior

Sometimes (not always), the device usage is related too `/`, not to the `tmpfs` directory.

##### Steps to Reproduce (for bugs)

1. Ensure that `/tmp` is on `tmpfs`, as is the case in most distros nowadays.
2. Open `/tmp` in pcmanfm-qt, without opening another folder. Show the File Properties dialog by right clicking *an empty space* insdie it. The Device Usage shown by File Properties dialog may be the same as what `df -h` shows. If not (quite possible), we have a bug. If it is, proceed to the next step.
3. Open `/` in another tab while keeping `/tmp` open. Then, see the Device Usage shown by File Properties Dialog by right clicking *an empty space* inside `/tmp`. It isn't what `df -h` shows but is the device usage of `/` instead.

##### System Information

Latest git LXQt.

**Comment by stefonarch** [comment]
In my arch it shows  358kb, with or without / open in another tab.
While  df -h says 7,0M:
```
df -h |grep "/tmp"
tmpfs                 3,9G  7,0M    3,9G   1% /tmp
```
I'll test on debian and will report.

**Comment by tsujan** [comment]
> In my arch it shows 358kb, with or without / open in another tab....

That isn't the device usage but total file size (excluding non-readable, root files). The device usage is shown by the progress-bar. Probably, you see it in your native language and the English term "Device Usage" misled you. Sorry, I should have mentioned the "progress-bar" in the report!

**Comment by stefonarch** [comment]
Ok, all clear, confirmed.

**Comment by tsujan** [comment]
Sadly, if the fix can't be backward-compatible, which means that, apart from recompilation of all `libfm-qt`-based apps, we should also edit the code of `pcmanfm-qt` too :(

**Comment by tsujan** [comment]
Made a simple compromise in https://github.com/lxqt/libfm-qt/pull/697, without needing any code change to `pcmanfm-qt` or other apps that are based on `libfm-qt` (although they *should* be recompiled).

I think it's justified because it should work in all our codes. Perfectionism would cause a headache.
