### ISSUE TITLE
Icon/thumbnail view's smooth scrolling may not work with some touchpads

### ISSUE THREAD

**Issue by xiota** [lxqt/libfm-qt#722]
**Description:** Scrolling in the icon and thumbnail modes freezes up when the cursor is over the folder view area.  Scrolling works fine when the cursor is positioned over the scrollbar.  

I first noticed the problem in [lximage-qt 4cd4e57](https://github.com/lxqt/lximage-qt/commit/4cd4e574da25302b56af3724b1747fd85173a104) using libfm-qt 0.17.1.  The problem also affects libfm-qt 1c38ef3.  Both pcmanfm-qt and lximage-qt are affected.  A video to demonstrate the problem is attached.

This problem occurs in two different desktop environments (KDE Plasma, Xfce) on two computer I tested.  I used both a touchpad and a trackball for testing.  I could not find a normal mouse.

**Expected Behavior:** Scrolling should "work".  It should not freeze up.

**Possible Solution:**  When I added IconMode and ThumbnailMode to the if statement, scrolling works as expected.  This may be related to lxqt/pcmanfm-qt#85, since a potential fix is the same.

Potentially related to #611.

**Environment:** 
* OS: Kubuntu 21.04
* Kernel: 5.10.??
* Qt Version: 5.15.2
* libqtxdg Version: 3.7.1 and [dcac08a](https://github.com/lxqt/libqtxdg/commit/dcac08a03317e544152570b954df41352618e6f9)
* lxqt-build-tools Version: 0.9.0
* Package version: 0.17.1 and 1c38ef3

https://user-images.githubusercontent.com/8353098/132129929-bb886b0a-e4ef-4d98-871d-f2a1427d0ad8.mp4

**Comment by tsujan** [comment]
Not reproducible.

Please add  System Information; it was in the template for a reason.

The report can be reopened if you give us a way of reproducing it.

**Comment by xiota** [comment]
@tsujan I added the info.  I just tested a third computer, Kubuntu 18.04, with an ancient version of libfm-qt and pcmanfm-16 and it does *not* appear to be affected.

**Comment by tsujan** [comment]
As I said, we need a way of reproducing it. I suspect you may be using bad builds —`libqtxdg` isn't the latest version, let alone the latest git, you may have mixed packages (old and git) or badly compiled packages, etc.

**Comment by xiota** [comment]
I'll try building libqtxdg from git to see if it makes a difference.

**Comment by xiota** [comment]
I tried building libqtxdg 3.7.1 from the deb packages and from git.  After each build, I rebuilt libfm-qt.  Then rebuilt lximage-qt.  No improvement.

**Comment by xiota** [comment]
I downgraded to the stock Kubuntu 21.04 packages and it still freezes up.  The reason I opened the issue is you had told me to a couple days ago.  It's annoying that when I actually do, you summarily close it in a few minutes.  You might as well mark it wontfix.

**Comment by tsujan** [comment]
I close unreproducible reports and will reopen them if the reporters give us a way of reproducing the issues. An issue can have tens of causes outside the code.

Taking this personally isn't helpful but people sometimes do so.

**Comment by xiota** [comment]
Closing it within a few minutes makes it so that anyone else who may have the same problem or have more info about reproducing it most likely won't see it.

**Comment by tsujan** [comment]
> so that anyone else who may have the same problem or have more info about reproducing it most likely won't see it.

They'll make a new report, especially when they have a way of reproducing it.

> Basically makes writing the report in the first place a waste of time.

Sorry that you feel so. The issue template and the way of handling issues are for preventing waste of time.

**Comment by tsujan** [comment]
I changed the title appropriately.

Although smooth scrolling always works fine with mouse wheel, it may not work with *some* touchpads. Fortunately, I have two laptops. In my work laptop, smooth scrolling has no problem when done by two-finger scrolling on the touchpad. But, in my old (and broken) laptop, it's jumpy with touchpad.

The fix is easy; will make a PR soon.

**Comment by xiota** [comment]
What version of Qt are you running?  Maybe it is a change in Qt that is causing my problems.

**Comment by xiota** [comment]
What version of Qt are you running? Maybe it is a change in Qt that is causing my problems.

**Comment by stefonarch** [comment]
5.15 quite sure in manjaro.

**Comment by xiota** [comment]
I just checked, there's a newer version of Qt: 5.15.6 (not counting the 6 line).  I'll just run a patched version of libfm-qt until this magically fixes itself.

**Comment by xiota** [comment]
@tsujan  I'm not going to open an issue for this.  What's the expected behavior when scrolling when inline renaming is active (with mouse cursor over folderview)?  What about when the mouse cursor is over the scrollbar?  Should the behavior during the two scenarios be the same or different?   What happens on your computer during those two scenarios?

**Comment by tsujan** [comment]
> You can answer the questions for yourself or not...

I overlook the above words for now.

Check the buggy behavior of Dolphin's inline renaming when you scroll a srollable name inside the editor, while the file is inside a scrollable view. Then compare it with pcmanfm-qt's behavior.

I'm afraid explaining codes in English is beyond my free time. Codes need to be read.

**Comment by xiota** [comment]
> I'm afraid explaining codes in English is beyond my free time. Codes need to be read.

I take this to mean that it does what it's supposed to, since it does appear to behave as it's coded.  I didn't bother opening an issue because I expected there's a good chance it would be closed with a comment saying it does what it's supposed (coded) to do.

> Check the buggy behavior of Dolphin's inline renaming...

What another file manager does is another issue.

**Comment by tsujan** [comment]
> What another file manager does is another issue.

I asked you to check it to save a long explanation.
