### ISSUE TITLE
PCManFM-Qt: Smooth Scrolling Adds Noticeable Delays to Detailed List Mode

### ISSUE THREAD

**Issue by Chiitoo** [lxqt/libfm-qt#739]
##### Expected Behavior

Less delay in moving to a directory or when re-sorting files in PCManFM-Qt.

##### Current Behavior

After 363233ef2e6 [1], smooth scrolling is enabled for PCManFM-Qt's Detailed List view, and this seems to add a noticeable delay to opening and/or re-sorting files.

The delay will probably only become longer with more files, starting to be very noticeable with approximately 5000 files on my system (Ryzen 7 1700, tested with SSDs and HDDs), becoming around one second with about 10000 files.

1. https://github.com/lxqt/libfm-qt/commit/363233ef2e6c8122627a03bd78a6357cb659b198

##### Possible Solution

At the very least it would be nice to have the option to disable smooth scrolling in Preferences (personally I might still prefer the non-smooth scroll regardless of this issue).

##### Steps to Reproduce (for bugs)

My current builds use the Qt upstream 5.15 git master branch, with the KDE patches applied on top.  I have not tested this with any official releases of Qt.

1. Create, or/and open a directory with 10000 files or more.
2. Click file name, type, size, modified, or any other columns to sort files.
3. Notice that the delay in both, opening the directory and sorting takes quite a bit longer than without the smooth scrolling commit.

##### Context

This seems to affect me surprisingly often, and albeit the delay usually is only around 1 second, it's not exactly fun either.  :]

##### System Information

* Distribution & Version: Gentoo Linux
* Kernel: Linux 5.14.11
* Qt Version: 5.15.2 With KDE Patches
* libqtxdg Version: git master (dcac08a0331)
* lxqt-build-tools Version: git master (426067cf026)
* Package version: git master (3470b204818)

**Comment by Chiitoo** [comment]
Seems to work as advertised.

Most excellent, thank you!

**Comment by tsujan** [comment]
Thanks for the fast reply!

Tomorrow, I'll read the patch again. If I find nothing suspicious, I'll merge it and add an option to pcmanfm-qt.
