### ISSUE TITLE
"Invert Selection", *in folder context menu*, seems redundant

### ISSUE THREAD

**Issue by tsujan** [lxqt/libfm-qt#743]
Because, once the user right clicks the containing folder, all selections will be cleared and "Invert Selection" won't be different from "Select All".

Of course, "Invert Selection" should be kept in pcmanfm-qt's Edit menu as it is now, with its shortcut (`Cttr+Shift+A`). But, in `libfm-qt`, we can't  — actually, we shouldn't — assign a shortcut to its context menu action. Therefore, I think it's a small design flaw and can be removed from libfm-qt's folder context menu.

There's also another possibility: we might want to remove it from the folder context menu and add it to the *file* context menu because right clicking a file inside a selection doesn't clear that selection.

**Comment by stefonarch** [comment]
Yes, completely unusable there.
