### ISSUE TITLE
Potential crashes in GObjectPtr

### ISSUE THREAD

**Issue by cepamoi** [lxqt/libfm-qt#751]
I'm not fully sure about these issues, but the code of GObjectPtr might be incorrect in some cases.

##### Expected Behavior
No crash with GObjectPtr, object references correctly handled.

##### Current Behavior
1. In function GObjectPtr& operator = (T* gobj), line 77 is:
`gobj_ = gobj ? reinterpret_cast<T*>(g_object_ref(gobj_)) : nullptr;
`
But I think it should be:
`gobj_ = gobj ? reinterpret_cast<T*>(g_object_ref(gobj)) : nullptr;
`
2. Constructor of GObjectPtr has a boolean add_ref to conditionally adds a reference to gobj (call to g_object_ref()).
But all the calls to g_object_unref() are unconditional. Is it intended?
Maybe add_ref should be kept as a member, and add_ref should be checked before calling g_object_unref().
For example:
```
if(gobj_ != nullptr && add_ref_)
     g_object_unref(gobj_);

```

##### Possible Solution
Se above.

##### System Information
* Distribution & Version: CentOS 7.3
* Kernel: 3.10.0-1127.10.1.el7.x86_64
* Qt Version: 5.15.2
* lxqt-build-tools Version: 0.10
* libfm-qt Version: 1.0.0

**Comment by tsujan** [comment]
> gobj_ = gobj ? reinterpret_cast<T*>(g_object_ref(gobj_)) : nullptr;

Yes, that's wrong (a typo) and should be fixed. Only by chance, it isn't used anywhere.

> But all the calls to g_object_unref() are unconditional. Is it intended?

Yes, that's how it's used by the code. If `add_ref` is `false`, the original object is also unrefed; if not, it'll remain intact.
