### ISSUE TITLE
Potential memory leak in fm_search_to_gfile

### ISSUE THREAD

**Issue by cepamoi** [lxqt/libfm-qt#753]
There is probably a potential memory leak in the fm_search_to_gfile() function.

##### Expected Behavior
No memory leak in the fm_search_to_gfile() function.

##### Current Behavior
A string is allocated in the main scope of the fm_search_to_gfile() function:
`GString* search_str = g_string_sized_new(1024);`
But it is freed only at the end of the `if(search->search_path_list)`:
```
GFile* fm_search_to_gfile(FmSearch* search)
{
    GFile* search_path = NULL;
    GString* search_str = g_string_sized_new(1024);
    ...
    if(search->search_path_list) /* we need to have at least one dir path */
    {
        ...
        g_string_free(search_str, TRUE);
    }
    return search_path;
}
```
This results in a memory leak when search->search_path_list is 0.
##### Possible Solution
Move the allocation of search_str inside the `if(search->search_path_list)`:
```
GFile* fm_search_to_gfile(FmSearch* search)
{
    GFile* search_path = NULL;
    ...
    if(search->search_path_list) /* we need to have at least one dir path */
    {
        GString* search_str = g_string_sized_new(1024);
        ...
        g_string_free(search_str, TRUE);
    }
    return search_path;
}
```
##### System Information
* Distribution & Version: CentOS 7.3
* Kernel: 3.10.0-1127.10.1.el7.x86_64
* Qt Version: 5.15.2
* lxqt-build-tools Version: 0.10
* libfm-qt Version: 1.0.0

**Comment by tsujan** [comment]
In practice, no memory leak happens because `fm_search_add_dir()` is always called before `fm_search_to_gfile()`. But you're right. For the sake of logic, the function should guarantee freeing after allocation.
