### ISSUE TITLE
std::unordered_map<const std::string, ...>

### ISSUE THREAD

**Issue by jwakely** [lxqt/libfm-qt#776]
Not a bug, but a bit of a code smell. Is there a good reason for using a const key type here?

https://github.com/lxqt/libfm-qt/blob/0c907dc01c062b3bd19d8078c9dfd5a6b65020bd/src/core/folder.h#L179

It's not wrong per se, but it's a bit weird, and prevents move semantics in some member functions of `unordered_map`.

If you just use `unordered_map` normally as intended to be used then you wouldn't need to specify the hash function explicitly:

```c++
std::unordered_map<std::string, std::shared_ptr<const FileInfo>> files_; 
```

Access to the keys of map elements is always const, because the map gives a `const key_type&` back, so there is no need to make `key_type` itself also be `const`.

**Comment by tsujan** [comment]
> Is there a good reason for using a const key type here?

No, there doesn't seem to be any. It's just that the focus has been on important fixes/workarounds in `Fm::Folder`.

Thanks for bringing this to our attention!
