### ISSUE TITLE
`Fm::IconInfo`, scale factor and symbolic icons: not a bug but details

### ISSUE THREAD

**Issue by tsujan** [lxqt/libfm-qt#788]
`Fm::IconInfo` correctly scales icons with scale factors > 1; actually, it lets Qt do it. It's responsible for icons inside pcmanfm-qt's (as well as LXQt file dialog's) view and side-pane. Other icons are controlled by Qt, whether directly or through an icon engine (like that of LXQt).

But, for example, with a scale factor of 2, LXQt's icon engine will choose symbolic icons for the sizes 16×2, 22×2 and 24×2 if the icon theme supports them, while `Fm::IconInfo` shows ordinary icons. The end result is sharp icons in both cases but `Fm::IconInfo` doesn't use symbolic icons with a scale factors of 2.

You could check that by launching `QT_SCALE_FACTOR=2 pcmanfm-qt` (after stopping `pcmanfm-qt` from LXQt session settings). If your icon theme supports symbolic icons, the toolbar icons will be symbolic but the side-pane and view icons won't.

Since `Fm::IconInfo` takes the icon name from `GIcon` and uses `QIconEngine` to find the icon, there doesn't seem to be a place in it for dealing with scale factors directly. So, I'm not sure this could be changed in future. However, IMO, it's better to have an open issue for it.

EDIT: See https://github.com/lxqt/libfm-qt/issues/788#issuecomment-1057998958 → 4, for why you might get confused by the Breeze icon set when testing this.

**Comment by palinek** [comment]
Can you, please, exactly describe icon names, themes etc. for me to replicate it. Maybe we can find a solution/workaround.

**Comment by tsujan** [comment]
Any icon set with SVG symbolic icons, like Breeze.

**Comment by tsujan** [comment]
> What does "symbolic" mean here?

They have simple forms and are usually monochrome. For coders, I should have said, "with stylesheets".

**Comment by tsujan** [comment]
Finally, and for the sake of completeness, this screenshot is taken with a scale factor of 2:

![scaled](https://user-images.githubusercontent.com/981076/156346854-90baa2b7-60d5-44aa-8143-741c7d9d3d1f.png)

The toolbar icons are still symbolic, but the side-pane and view icons aren't because libfm-qt's icon engine interferes with that of LXQt.

**Comment by palinek** [comment]
> but Fm::IconInfo doesn't use symbolic icons with a scale factors of 2.

It is using what is provided by the icon theme. E.g. the desktop folder -> icon `user-desktop`, this is what is provided by breeze:
```
$ find /usr/share/icons/breeze -name user-desktop\* -exec ls -l {} \; | sort -k8,8
-rw-r--r-- 1 root root 452 2022-01-01 13:10 /usr/share/icons/breeze/places/16/user-desktop.svg
-rw-r--r-- 1 root root 427 2022-01-01 13:10 /usr/share/icons/breeze/places/22/user-desktop.svg
-rw-r--r-- 1 root root 6069 2022-01-01 13:10 /usr/share/icons/breeze/places/32/user-desktop.svg
-rw-r--r-- 1 root root 3733 2022-01-01 13:10 /usr/share/icons/breeze/places/48/user-desktop.svg
-rw-r--r-- 1 root root 8415 2022-01-01 13:10 /usr/share/icons/breeze/places/64/user-desktop.svg
-rw-r--r-- 1 root root 7003 2022-01-01 13:10 /usr/share/icons/breeze/places/96/user-desktop.svg
lrwxrwxrwx 1 root root 26 2022-02-11 23:46 /usr/share/icons/breeze/places/symbolic/user-desktop-symbolic.svg -> ../16/folder-documents.svg
```
![screenshot](https://user-images.githubusercontent.com/10990929/156376157-bc48f861-60a3-4e97-86e6-395ebd159227.png)
![screenshot](https://user-images.githubusercontent.com/10990929/156376222-22c5d01b-417d-46fb-9e56-ef948b517c43.png)
![screenshot](https://user-images.githubusercontent.com/10990929/156376276-6379c8b7-5659-4113-87e1-20871ccf5850.png)
![screenshot](https://user-images.githubusercontent.com/10990929/156376322-3147b34f-041c-4fae-aa9b-625254f8bc75.png)
![screenshot](https://user-images.githubusercontent.com/10990929/156376388-022d2d0f-e55d-4769-af0d-7a3367763273.png)
![screenshot](https://user-images.githubusercontent.com/10990929/156376441-56e3a4fb-c514-470b-82ea-abaf072c6a14.png)
![screenshot](https://user-images.githubusercontent.com/10990929/156376495-45ce9254-75dc-47fb-b6d6-d763d8e56cef.png)

So the theme icon engine just follows the decision made by icon theme. (with the scale factor > 1 there is never requested icon smaller than 32)

**Comment by tsujan** [comment]
No! Breeze also has `16@2x`, `22@2x` and `24@2x` folders. They are for being used with scaling. If you remove `Fm::IconEngine` (→ https://github.com/lxqt/libfm-qt/pull/789), LXQt icon engine will show them correctly.

**Comment by palinek** [comment]
Oh sorry... missed that.
Then the cause is is in `IconEngine::virtual_hook`... I see it now.

I have something in my mind, need to test if it can solve this problem.

**Comment by palinek** [comment]
Please, what icon theme are you using and which showed icons are you considering to be shown wrongly?

**Comment by tsujan** [comment]
> Please, what icon theme are you using

It makes no difference; the "problem" appears with all icon themes that have symbolic icons. I use https://github.com/tsujan/Plataro but, IMO, Breeze is better for testing

This is a screenshot of LXQt file dialog with a scale factor of 2 and Breeze:

![breeze](https://user-images.githubusercontent.com/981076/156525521-da0446e1-1d31-4c29-8547-350b0e67f934.png)

Like in my other screenshot, no view/side-pane icon is symbolic, but all would be symbolic if `Fm::IconEngine` was removed.

**Comment by palinek** [comment]
Yes, but it depends what sizes you configured
* size of small icons 22px
![screenshot](https://user-images.githubusercontent.com/10990929/156533829-22dc158d-583d-4e9b-b722-f028a1a3b0b6.png)
* size of small icons 28px
![screenshot](https://user-images.githubusercontent.com/10990929/156534312-aaf47899-a8a4-47fe-949d-919bbc66900c.png)

...and based on some tests, icons in left pane have different size for pcmanfm-qt & lxqt file dialog, I'll check this further.

**Comment by tsujan** [comment]
* Side-pane icons are 24-pix.
 * Fusion isn't self-consistent with 22-pix (and the Breeze widget style seems to inherit that). Either use 24-pix view icons to see the problem in the view or forget about the view and focus on the side-pane. (Kvantum is self-consistent.)
 * There's no 28-pix symbolic icon in Breeze (and in most icon sets).
 * In a nutshell, *where you see symbolic icons without a scale factor, you should also see symbolic icons with a scale factor of 2*, provided that you use the Breeze set.

**Comment by tsujan** [comment]
This screenshot is taken with the Breeze set and a scale factor of 3 and, again, shows that LXQt icon engine has no problem:

![scaled_3](https://user-images.githubusercontent.com/981076/156554161-e611705e-4c41-4571-b4d7-c3fa6c2e71c4.png)

The toolbar icons are 16-pix (in Kvantum), their pixmaps have a device pixel ration of 3, and all of them are symbolic (except for the rightmost one, which doesn't have a symbolic icon at all).

**Comment by palinek** [comment]
Can you have a look in #792?

**Comment by tsujan** [comment]
> Can you have a look in https://github.com/lxqt/libfm-qt/pull/792?

I did. Please also read my comment about the Breeze set there. Problem inside Problem...

**Comment by tsujan** [comment]
Let's summarize it again, for the sake of removing confusions (if you don't agree with what follows, please tell me):

 1. With the current internal icon engine of libfm-qt (namely, `Fm::IconEngine`), scaled symbolic icons aren't picked up by the side-pane or view.
 2. If we remove `Fm::IconEngine`, scaled symbolic icons reappear (because LXQt's icon engine works fine).
 3. With something like https://github.com/lxqt/libfm-qt/pull/792, scaled symbolic icons reappear too.
 4. The Breeze icon set can be very confusing in this regard because it doesn't include `places/24@2x` in its `index.theme`. If you want to test what's explained in the first comment of this report, use an icon set that really has *scaled, symbolic, places icons*.

**Comment by tsujan** [comment]
Problem solved, at last: https://github.com/lxqt/libfm-qt/pull/1015.  It was caused by a bad scaled pixmap. But it couldn't be fixed with Qt5, because a needed `QIcon` method didn't exist there.
