### ISSUE TITLE
Drag'n'drop'ed files paths from PCManFM-Qt are not escaped/quoted

### ISSUE THREAD

**Issue by brainrom** [lxqt/libfm-qt#793]
##### Expected Behavior

When I drag'n'drop files I expect it to be properly escaped to use it in terminal emulator.

##### Current Behavior

PCManFM-Qt provides an unescaped file paths 

##### Possible Solution

Implement a file path escape or quoting on drag'n'drop and clipboard file copying.

##### Steps to Reproduce (for bugs)

1. Open a terminal and start to write any command with the file name as argument 
2. Drag'n'drop file, which path contains spaces and other special symbols to the terminal from PCManFM-Qt
3. Filename will be split to different command arguments (in case of spaces) or not be read properly.

##### Context

I want to use a command line tools which accepts multiple files as arguments (such as pdfunite) without manually writing it's names. KDE Dolphin have such feature.

##### System Information

* Distribution & Version: Artix Linux
* Kernel: 5.16.10-artix1-1
* Qt Version: 5.15.3+kde+r132-1
* libqtxdg Version: 3.8.0-2
* lxqt-build-tools Version: 0.10.0-1
* Package version: git version

I will try to fix it by myself and provide a suitable PR.

**Comment by tsujan** [comment]
The receiver is responsible for whatever it wants to do with the path, not the source.
