### ISSUE TITLE
"Visible columns" and "auto-resize" not persistent. 

### ISSUE THREAD

**Issue by J-Dunn** [lxqt/libfm-qt#804]
One thing I find really annoying is the displayed columns in detailed file view. If I right-click on any column heading I can configure what columns show ( eg get rid of the moronic "Types" column that eats space to state the bleedin' obvious).

I can deactivate this column but it is back to bug me next time I need to use the dlg. Same for Auto-resize.

Not much point in configuring these options ( which is cool ) if they get forgotten straight away.

##### Expected Behavior
If I configure "Visible columns" ( all selected by default)  or uncheck "auto-resize" these settings are not retained at the next invocation of the open file dialogue.

##### Current Behavior
Visible columns and auto-resize are not retained. 

##### Steps to Reproduce (for bugs)
1. Open a program which uses qt open/save dialogues ( FeatherPad )
2. File | Open
3. Rightclick "Type" column header; uncheck
4. Uncheck "auto-resize"
5. open a file
6. File | Open
7. observe that columns are back to default: auto=on , type visible.

##### Context
Having to possibility to configure columns is great. "Type" in particular is usually total cruft on any sensible OS which is not removing file extensions from file names. eg. index.html, I do not need the dlg to tell me it is an "HTML document".  

Due to it's prominent position ( second column ) it eats up valuable screen space which can prevent other information from being easily read ( date/time info ).  It is great to have this configurable but it is really annoying and detrimental to work flow to have reconfigure columns to what is needed for clearly displaying what is present every time the file dlg is used. 

Certain contexts may have long file names which get truncated in auto-resize. I should not need to have to reconfigure at each use because unchecking auto-resize is not retained. 

These are great features to have but much less use if they are not retained. 

##### System Information
* Fedora 34
* Kernel: 5.11.19
* Qt Version: 5.15.2
* libqtxdg Version: 3.6.0
* lxqt-build-tools Version: 
* Package version: 0.16.0

**Comment by stefonarch** [comment]
> Package version: 0.16.0
> libqtxdg Version: 3.6.0

Versionis far  outdated, issue is not reproducible, fixed time ago.

**Comment by J-Dunn** [comment]
Thanks , in what version was this fixed ?

**Comment by stefonarch** [comment]
@tsujan may remember it.

**Comment by tsujan** [comment]
Visible columns are remembered in 1.0.0. The latest release is 1.1.0.

"Auto-resize" is kept as a temporary change (not remembered). I didn't find it so useful, but it can be implemented easily.

@stefonarch 
What do you think? Should "Auto-resize" be remembered too?

**Comment by stefonarch** [comment]
I thought it was, I see  it changes to "checked" at next time if unchecked. 
Personally I can't see any use of not autoresizing - but if we have an option it should be remembered.

**Comment by tsujan** [comment]
OK. I'll make a PR.

**Comment by J-Dunn** [comment]
> OK. I'll make a PR.

thanks.

> Personally I can't see any use of not autoresizing

maybe you did not read the bug report then.

>  issue is not reproducible, fixed time ago.

Next time _try_ to reproduce it before closing the issue saying you cannot reproduce. Thanks.

**Comment by tsujan** [comment]
> Next time try to reproduce it before closing the issue saying you cannot reproduce.

Next time try to read the issue template. It says, "Please do NOT file bugs against old (dead) versions".

**Comment by stefonarch** [comment]
> Next time _try_ to reproduce it before closing the issue saying you cannot reproduce. Thanks.

> Visible columns and auto-resize are not retained.

I did, but didn't check both, sorry.

**Comment by J-Dunn** [comment]
> I did, but didn't check both, sorry.

Fair enough. Thanks for recognising the slip up.

**Comment by tsujan** [comment]
> Since you do not define "old ( dead) " that is open to broad interpretation.

"Old" means any version other than the latest release. V1.0.0 is old now.

We may find useful info in reports that are made against old versions, but they're often closed.
