### ISSUE TITLE
Issue in rubber-band selection of icon view

### ISSUE THREAD

**Issue by tsujan** [lxqt/libfm-qt#815]
Although users usually don't encounter this situation, it's a bug:

1. In pcmanfm-qt's icon view, press the left mouse button inside an empty space and keep it pressed while dragging, to create a rubber-band selection.
2. While the left mouse button is pressed, stop moving the cursor and press the right button, to trigger the context menu.
3. Then release both mouse buttons and press `Escape` to close the menu.

Now, if you move the mouse cursor inside the view without pressing any mouse button, the rubber-band will follow the cursor.

The expected behavior is that the rubber-band selection shouldn't continue without the left mouse button being pressed.

In the detailed list mode, the rubber-band selection freezes at (3), which is more acceptable (although not ideal).

EDIT: In the title, I wrote "list view" but meant icon view. My mistake was because icon view uses `QListView` ;) Corrected the title.

**Comment by tsujan** [comment]
It's a little confusing:

**a**. I made a simple list-view with rubber-band selection and context menu. The rubber-band selection froze at (3).
**b**. In another test, I changed libfm-qt's code to use only Qt's mouse press, move and release events in the icon view, but the problem persisted.

(a) suggests that the problems is our, while (b) does the opposite.

**Comment by stefonarch** [comment]
>While the left mouse button is pressed, stop moving the cursor and press the right button, to trigger the context menu.

This is impossible to do  with my touchpad which has no physical buttons....

**Comment by tsujan** [comment]
> This is impossible to do with my touchpad which has no physical buttons....

If you have a Menu key on your keyboard, you could press it instead of of right clicking. That context menu ruins rubber-band selection; it isn't important how it's triggered. The procedure should be done in *icon* the view.

Most users don't encounter this problem, but I don't like it.

**Comment by stefonarch** [comment]
>If you have a Menu key...
Never use it for menu, but yes I see it. But one tap makes it disappear.

**Comment by tsujan** [comment]
OK, it's definitely a Qt bug. It's related to ["mouseTracking"](https://doc.qt.io/qt-6/qwidget.html#mouseTracking-prop) in `QListView`. Once I added mouse tracking to my minimal test code, I saw the same thing.

Even without mouse tracking, `QListView` has a buggy behavior under the circumstances described in the first comment, but it's a little milder.

**Comment by tsujan** [comment]
For reference, the minimal code is attached:

[listwidget.zip](https://github.com/lxqt/libfm-qt/files/9125539/listwidget.zip)
