### ISSUE TITLE
CMake configure fails to check for qpa/qplatformdialoghelper.

### ISSUE THREAD

**Issue by eyalroz** [lxqt/libfm-qt#845]
I've just downloaded and tried to build v1.1.0 on 

CMake configure passed, but - when I try to build, I get:
```
/usr/local/src/libfm-qt-1.1.0/build/src/fm-qt_autogen/EWIEGA46WW/../../../../src/filedialoghelper.h:5:10: fatal error: qpa/qplatformdialoghelper.h: No such file or directory
    5 | #include <qpa/qplatformdialoghelper.h> // this private header is subject to changes
```

##### System Information
* Distribution & Version: Devuan Deadalus (~= Debian Bookworm without systemd).
* Kernel: 5.19.0-2-amd64
* Qt Version:  
* libqtxdg Version: 
* lxqt-build-tools Version: 
* Package version: 1.1.0

**Comment by eyalroz** [comment]
This was circumvented by installing Debian packages qtbase5-private-dev and qtbase6-private-dev ; possibly just one of them would have sufficed.

**Comment by tsujan** [comment]
Not a libfm-qt issue.

As for Debian, `qtbase5-private-dev` is a build dependency (→ http://deb.debian.org/debian/pool/main/libf/libfm-qt/libfm-qt_1.1.0-3.debian.tar.xz), but that isn't related to the upstream.

**Comment by tsujan** [comment]
Also → https://github.com/lxqt/lxqt/wiki/Building-from-source#debian-derivates-1

**Comment by eyalroz** [comment]
If it's a build dependency, and it's missing, the CMake configuration should fail. That's the issue.

**Comment by tsujan** [comment]
It's Debian that packages it separately; so, it's Debian that should take care of it.

**Comment by eyalroz** [comment]
@tsujan : I don't expect the library's CMake to "take care of it", but it does need to check whether it has everything it needs. It should emit an error saying "I'm missing QT component [whatever]" - not say that everything is ok, then let the build itself fail.
