### ISSUE TITLE
libfm-qt6: Emptying Trash (in LXQt file dialog) causes a crash

### ISSUE THREAD

**Issue by tsujan** [lxqt/libfm-qt#871]
As the title says. You could test with any Qt6 app that uses LXQt file dialog if you have installed Qt6 WIP branches. If you try to empty Trash from the dialog — even when you cancel the operation — the dialog (and the app) will crash.

@stefonarch 
If you still have installed Qt6 branches, would you please confirm this? There's no need to update your installation of Qt6 branches.

**Comment by tsujan** [comment]
OK, not only emptying Trash but also mounting by using the context menu can lead to a crash. For whatever reason, Qt6 will cause a crash if the main event loop is blocked here. Fortunately, the workaround is simple.

I guess a similar problem happened several years ago, and PCMan circumvented it by using `QMenu::popup()` instead of `QMenu::exec()`. That workaround is still needed but should be completed for Qt6.

**Comment by stefonarch** [comment]
Ok, confirming: featherpad, opening filedialog and emptying trash will crash both, without emptying it.
Mounting a internal partition will mount it and crash afterwards.

**Comment by tsujan** [comment]
@stefonarch, thanks a lot!

Fixed in https://github.com/lxqt/libfm-qt/pull/778/commits/aa82aa82509bbbac92ae20954f85a4871e14655a. Strange way of closing an issue with a WIP commit ;)
