### ISSUE TITLE
Extra CPU time taken by folders containing many desktop entries

### ISSUE THREAD

**Issue by tsujan** [lxqt/libfm-qt#874]
When a folder with many desktop entries (e.g., /usr/share/applications/) is opened, the CPU usage is more than other folders. The amount of extra CPU usage doesn't seem normal to me, whether in LXQt file dialog or in pcmanfm-qt.

This page is opened for more investigation.

**Comment by stefonarch** [comment]
True, my guess it because there is no cache for desktop entries icons.

**Comment by tsujan** [comment]
I had the same thought, but further investigation showed that the cache existed and worked fine.

Then, I thought that reading of desktop entries might be CPU-intensive, but that theory proved to be wrong too.

I'm suspicious of GLib: some of its icon functions may cause this. There should be a reason why Nautilus doesn't show desktop icons by default (it didn't a year ago, when I tested it).

**Comment by tsujan** [comment]
BTW, I found a reason to generalize the option for disabling smooth scrolling: here, it's choppy with a maximized window inside `/usr/share/applications/`. Smooth scrolling itself isn't the culprit, because it's really smooth inside a folder with more than 600 different icons (from an icon set) or elsewhere.

At least some users will be happy ;)

**Comment by tsujan** [comment]
Mystery solve!. The culprit is nether GLib nor Qt, but [this line in pcmanfm-qt](https://github.com/lxqt/pcmanfm-qt/blob/b437f499db28e7a0ec004c28826725b621f8ecd6/pcmanfm/application.cpp#L241-L242): 

```cpp
        // decrease the cache size to reduce memory usage
        QPixmapCache::setCacheLimit(2048);
```

While developers of some well-known desktop environments justify wasting of system resources by telling how "modern computers" can handle it, we think in terms of 20th century computers. Even if we care for ancient systems, we should prioritize CPU over RAM by leaving the cache to Qt (10240 KB by default).

Long story made short, although the first loading of `/usr/share/applications/` after a boot takes longer compared to other folders, its extra CPU usage after that is only because of the above line.

I'll test for a while and then remove that line if everything goes well.
