### ISSUE TITLE
Saving a file without its file extension takes the default literally

### ISSUE THREAD

**Issue by Daenarii** [lxqt/libfm-qt#879]
If I remove the highlighted text on the save dialog, it will fall back into saving as what is on the File type literally. 
![image](https://user-images.githubusercontent.com/16044253/216979250-7a99b207-1a54-4661-9d4c-00690d31a5ae.png)
Here's how the file was saved with the full filename shown:
![image](https://user-images.githubusercontent.com/16044253/216979632-fc59c37e-f98f-4e9a-b90a-7ca3504daf0f.png)
(ignore the file being detected as a webpage as it is probably Pcmanfm reading it)

This isn't that of a problem as it already filled out the file extension and will only break if you manually choose. But there were cases when I saved files before (I think those were images) and didn't have the file extension on the save dialog, so I had to either add .png manually or rename the .[pP][nN][gG] on the file manager.
Doesn't matter if it has or has no file extension added when you save something, it should have a good fallback to save the file type properly.

I assume it should default out to the file extension on lowercase.

**Comment by tsujan** [comment]
The problem was in `libfm-qt`, and this is the fix: https://github.com/lxqt/libfm-qt/pull/880
