### ISSUE TITLE
Enter key for SaveAs sometimes does not enter directory.

### ISSUE THREAD

**Issue by humpity** [lxqt/libfm-qt#885]
Enter key for SaveAs sometimes does not enter a directory.

##### Expected Behavior

Enter key should always enter a directory in a SaveAs dialog.

##### Current Behavior
If the mouse is used (double-click), there is no problem.
If the filename field is empty, there is no problem.
If the filename field is not empty (as is the default from some apps or if the selection had moved over a file). Then that file is saved in the directory under the selection. And the dialog closes.

##### Possible Solution
Enter key should only save a file if the selection is over a file, not a directory.

##### Steps to Reproduce (for bugs)
1.  Open a qt app e.g kwrite and choose SaveAs.
2. If the filename field is empty, move selection over a file or type it in.
3. Use arrow keys or mouse to move selection over a directory.
4. Press Enter.
5. Instead of entering directory, the file is saved inside of it. This means you cannot further navigate into sub-directories.

##### Context
Save a file under several sub-directories using keyboard navigation.

##### System Information

* Distribution & Version: Lubuntu 22.04.1 LTS & 22.10
* Kernel: 
* Qt Version: 0.17.0 & 1.1.0
* libqtxdg Version: 
* lxqt-build-tools Version: 
* Package version:

**Comment by tsujan** [comment]
You're right; `ENTER` should enter the selected directory. Thanks for the report!

**Comment by tsujan** [comment]
There's also another problem with `ENTER` in the save-as dialog: if it's pressed over a file, the prompt dialog might be shown twice.
