### ISSUE TITLE
Update `archivers.list` and `lxqt-archiver` after recent changes in some MIME type strings

### ISSUE THREAD

**Issue by Bluey26** [lxqt/libfm-qt#938]
Hello.

I have noticed something strange in pcmanfm. I use last version, updated a few days ago, and i still do not see the 'Extract to...' for .tar.bz2 files. I use lxqt-archiver as my default file extractor.

I checked up a bit about this, got some help in the lxqt channel, and found this:

https://github.com/lxqt/libfm-qt/blob/master/data/archivers.list
https://github.com/lxqt/pcmanfm-qt/wiki/custom_actions

In there, its listed somehow, the file options and the formats 'recognized' by pcmanFM.
I also found the way to create 'custom actions', and make an action for this for the meanwhile.

I really do not know if this is exactly how it works, but  i found that .tar.bz2 mimetype is `x-bzip2-compressed-tar` (obtained from pcmanfm-qt, properties action) and searching in the link listed (should be the last version of that one) i have not found the mimetype under the 'lxqt-archiver' section (first one).

In the other hand, 'squeeze' and 'xarchiver' does indeed have those options, and since i have not those programs installed, i guess that pcmanfm 'thinks' that i have not the adequate programs/files to open that format.

I have checked that i can open with 'lxqt-archiver' the .tar.bz2 files, and i can also extract them using the program GUI or the command line:

`lxqt-archiver -h FILE.tar.bz2`

At the moment, my 'extract_to.desktop' action looks like this:

```
[Desktop Entry]
Type=Action
Name=Extract to...
Icon=none
Profiles=profile-zero;

[X-Action-Profile profile-zero]
Exec=lxqt-archiver -h %F
Name=Default profile

```

##### Expected Behavior

'Extract to...' should be present on .tar.bz2 files actions(right click on pcmanfm-qt)

##### Current Behavior

Option is not present (only 'compress' option present).

##### Possible Solution

Adding the corresponding format into the archives.list of libfm-qt or creating a custom.desktop file-action to support it in those cases that this is not present.

In case this is not added for some specific reason, i would really appreciate if you could help me to improve the .desktop i have shared. It should be only be present for .tar.bz2 files (now is shown in every file and action) and i also would like to have it in the 'vanilla' way, under the 'Compress' option, like the other compressed files. I do not know how to do this last part either. I attach a picture to show how is looking now (the 'Extract to...' is the one added by me in the left image)

##### Steps to Reproduce (for bugs)

1. Creating a .tar.bz2 file or downloading one
2. Going to the download directory using pcmanfm-qt
3. Try to extract the file using the menu actions(right click).

##### Context

Described in 'summary' section.

##### System Information

* Distribution & Version: Arch Linux, last update
* Kernel: 6.6.1-arch1-1
* Qt Version: 5.15.11
* libqtxdg Version: 3.12.0-1
* lxqt-build-tools Version: 0.13.0-1
* Package version: libfm-qt = 1.4.0-1

![currentanddesired](https://github.com/lxqt/libfm-qt/assets/143142826/2e9b2356-82f4-407e-bac3-a366a161cd48)

PS: `bzip2` is installed. Reinstalling `bzip2`, `lxqt-archiver` or `pcmanfm-qt` did not change the behaviour

**Comment by tsujan** [comment]
Some MIME type strings have been changed recently (by the responsible package, whose name I've forgotten). See https://github.com/tsujan/Arqiver/commit/92f7340d2f674e88effadcb4ed250432e331e687 for some examples. The changes aren't limited to archives though.

**Comment by tsujan** [comment]
Although the upstream changes weren't backward compatible, apps can make backward compatible changes. Arqiver is ready, but `lxqt-archiver` and probably most of the other archive managers in the list aren't. So, we may have to wait a little before changing `archivers.list`.

Also, icon themes may need to be updated because of the affected MIME types (for example, `text/x-dart` is changed to `application/vnd.dart`, `application/x-yaml` to `application/yaml`, `application/x-java-archive` to `application/ava-archive`, etc.).

**Comment by Bluey26** [comment]
Excellent. As always, thanks for your fast answers!

I have realized the correct commands were already present in the actual `archivers.list` , so for the moment i decided to 'mimic' those to have the options in those files, since changing the archivers.list may not be the best idea in this moment, as you said.

I created the folders and files as it is explained in [https://github.com/lxqt/pcmanfm-qt/wiki/custom_actions](url) (For those who may have the same problem) and i have created the following files (the .desktop name seems to not matter):

Extract_to_bz2.desktop:

```
[Desktop Entry]
Type=Action
Name=Extract to...
Icon=none
Profiles=profile-zero;

[X-Action-Profile profile-zero]
MimeTypes=application/x-bzip2-compressed-tar;
Exec=lxqt-archiver --extract-to %d %U
Name=Default profile
```

Extract_here_bzip2.desktop:

```
[Desktop Entry]
Type=Action
Name=Extract Here
Icon=none
Profiles=profile-zero;

[X-Action-Profile profile-zero]
MimeTypes=application/x-bzip2-compressed-tar;
Exec=lxqt-archiver --extract %U
Name=Default profile
```

Saving those files in the  folder specified in the link, and them 'restarting' the 'Desktop' (Session Settings > LXQt Modules and then stop to 'Desktop) will apply those things in the current session.

The  `x-bzip2-compressed-tar` seems to be the one who provides the options only for the `.tar.bz2` files i have.
It was obtained from your examples list, from this specific section [URL](https://github.com/tsujan/Arqiver/commit/92f7340d2f674e88effadcb4ed250432e331e687#diff-1c1ace710087ca3a20e9e219ef9cc51a354b0f06c64259347e51118b40947ff8)

The only thing i was not able to control was the order of the options, and that the 'compress' option should not be present in this file.
Those things are small details for the moment, the important it to have this 2 options for easily manage the files.

Thank you very much.

Bluey.

**Comment by tsujan** [comment]
I'll update `lxqt-archiver` soon (some care is also required because of the changes to `application/vnd.appimage` and `application/x-raw-disk-image`). Then I'll update `archivers.list` for `lxqt-archiver` and Arqiver. Other archive managers could wait.

**Comment by tsujan** [comment]
BTW, the package is `shared-mime-info` V2.3. For a long time, `bz2` was seen as `application/x-bzip` (old and deprecated). That's corrected now.

IMHO, when shared-mime-info-2.3 enters Debian Testing, we could migrate to new strings in our releases. However, doing it sooner in git seems good, especially for Arch/Manjaro users.
