### ISSUE TITLE
Add "Downloads" to places menu

### ISSUE THREAD

**Issue by mjkrg** [lxqt/libfm-qt#945]
The user home "Downloads" directory is now widely used across several operating systems that it should be considered a top-level item as "Desktop".

##### Expected Behavior

"Downloads" should show as an item under the Places menu.

##### Current Behavior

"Downloads" does not show in Places menu.

##### Possible Solution

```
--- placesmodel.cpp	2023-11-05 11:14:27.000000000 +0000
+++ placesmodel.cpp	2023-12-19 16:29:52.683844000 +0000
@@ -55,6 +55,10 @@
                                       Fm::FilePath::fromLocalPath(QStandardPaths::writableLocation(QStandardPaths::DesktopLocation).toLocal8Bit().constData()));
     placesRoot->appendRow(desktopItem);
 
+    downloadItem = new PlacesModelItem("user-download", tr("Downloads"),
+                                      Fm::FilePath::fromLocalPath(QStandardPaths::writableLocation(QStandardPaths::DownloadLocation).toLocal8Bit().constData()));
+    placesRoot->appendRow(downloadItem);
+
     createTrashItem();
 
     computerItem = new PlacesModelItem("computer", tr("Computer"), Fm::FilePath::fromUri("computer:///"));
``` 

##### Steps to Reproduce (for bugs)

1. Launch the PCManFM-Qt application
2. Right-click on any item on the Lists side pane
3. Click "Show All Entries"
4. "Downloads" is not listed under Places

##### Context

I've resorted to creating a bookmark for "Downloads". However, since one cannot inject a separator bar between bookmark items, visual context for higher priority items is harder to establish when you have many bookmark locations. 

##### System Information

* Distribution & Version: N/A
* Kernel: N/A
* Qt Version: N/A
* libqtxdg Version: N/A
* lxqt-build-tools Version: N/A
* Package version: N/A

**Comment by tsujan** [comment]
Any folder defined in `~/.config/user-dirs.dirs` may be widely used.

Use a bookmark -- its icon is distinguished enough.

**Comment by wesinator** [comment]
> Any folder defined in `~/.config/user-dirs.dirs` may be widely used.
> 
> Use a bookmark -- its icon is distinguished enough.

@tsujan what's the argument for not having the most common, or all the user-dirs in places by default?

[NO_TRAIN]::

**Comment by tsujan** [comment]
> what's the argument for not having the most common, or all the user-dirs in places by default?

A word that I often use when answering such questions: cluttering.
