### ISSUE TITLE
Rmdir installation error on Qt6

### ISSUE THREAD

**Issue by isf63** [lxqt/libfm-qt#955]
```
-- Installing: ~/.cache/yay/libfm-qt-git/pkg/libfm-qt-git/usr/share/mime/packages/libfm-qt6-mimetypes.xml
rmdir: failed to remove '~/.cache/yay/libfm-qt-git/pkg/libfm-qt-git/usr/include/libfm-qt/tests': No such file or directory
rmdir: failed to remove '~/.cache/yay/libfm-qt-git/pkg/libfm-qt-git/usr/include/libfm-qt/translations': No such file or directory
==> ERROR: A failure occurred in package().
    Aborting...
 -> error making: libfm-qt-git-exit status 4
 -> Failed to install the following packages. Manual intervention is required:
libfm-qt-git - exit status 4
```

**Comment by stefonarch** [comment]
Try removing the cache for it in `~/.cache/yay/`

**Comment by tsujan** [comment]
That's a problem related to `yay`. Please forget it and make a package directly: lxqt-build-tool → libfm-qt

**Comment by isf63** [comment]
It was `yay` misbehaving. Never got it to work, but installed fine manually.

**Comment by tsujan** [comment]
> but installed fine manually.

Preferably, make an installable package first (by using `makepkg`); otherwise, you might get into troubles later.

**Comment by isf63** [comment]
Aha! Yay printed `==> ERROR: A failure occurred in package().` and that lead me to inspecting the PKGBUILD. There is an error in:
```
package() {
  cd build

  make DESTDIR="$pkgdir" install

  # CMake installs empty folders unexpectedly
  # https://gitlab.kitware.com/cmake/cmake/issues/17122
  rmdir "$pkgdir"/usr/include/libfm-qt/{tests,translations}
 }
```
Using `yay --editmenu libfm-qt-git`, change /libfm-qt/ to /libfm-qt6/ and it successfully installs.

**Comment by stefonarch** [comment]
AUR packages aren't updated all yet:
https://gitlab.com/yan12125/aur/-/issues/42

**Comment by tsujan** [comment]
Closing because it isn't LXQt's problem.
