### ISSUE TITLE
Allowing pasting of full path into "File name" entry?

### ISSUE THREAD

**Issue by tsujan** [lxqt/libfm-qt#962]
That wouldn't be self-consistent for obvious reasons, but since Qt's default file dialog supports it, we might also want to do so.

If it's going to be done, the implementation should be as self-consistent as possible— for example, the completer should work if the pasted path is inside the current directory, or the path may need to be removed in that case,… — hence self-assigning.

**Comment by tsujan** [comment]
Will be done after LXQt 2.0.0 (which be released soon) because, contrary to the appearances, it'll need several considerations and thorough testing.

**Comment by rodrigo-j-goncalves** [comment]
Cool!! Thank you so much for considering this!!!

**Comment by tsujan** [comment]
@rodrigo-j-goncalves
The PR is here: https://github.com/lxqt/libfm-qt/pull/964. If you have LXQt 2.0.0 and can make package from source, please test it. Otherwise, we're testing it, and it'll be in 2.1.0 if there's no issue.
