### ISSUE TITLE
libfm-qt still requires gtk2

### ISSUE THREAD

**Issue by bdubbs** [lxqt/libfm-qt#963]
libfm-qt requires menu-cache which requires libfm-extra which requires gtk2

##### Expected Behavior
We need to be able to build lxqt without requiring (directly or indirectly) gtk2

##### Context
linuxfromscratch wants to remove gtk2 because it has been at EOL since the end of 2020,  The reason we moved from lxde  to lxqt was to support that.  The only other package we have that uses gtk2 is gimp and that is scheduled to be released without gtl2 next month.

Having users build gtk2 and its dependency chain just to support libfm-qt (I repeat QT) and therefore lxqt is not reasonable.

**Comment by tsujan** [comment]
> libfm-qt requires menu-cache which requires libfm-extra which requires gtk2

libfm-extra does not requite gtk2.

**Comment by bdubbs** [comment]
I made a mistake about dependencies.  I misread glib2 for gtk2. Please close the issue.

**Comment by tsujan** [comment]
Already closed.

LXQt doesn't depend on any version of GTK.
