### ISSUE TITLE
Side Pane font does not change on-the-fly anymore (regression?)

### ISSUE THREAD

**Issue by Bluey26** [lxqt/libfm-qt#979]
##### Expected Behavior

Changing the color palette should change the font color (foreground) of the 'Side Pane' items according to the theme, as every other fonts does inside the program.

##### Current Behavior

Side Pane fonts keep in black/dark color after setting the 'Dark' Palette in LXQt Appearance.
Re-opening the program applies the change. Strangely, this  only happens with the 'Side Pane' texts, everything else in the program changes accordingly.

This also happens in the inverse way: Going from the dark palette to the default palette makes all 'Side Pane' Texts become unreadable (the foreground color is white/gray and should be black/darker as the other texts in the program).

##### Possible Solution

No idea.

##### Steps to Reproduce (for bugs)

I am not sure if this is reproducible for other persons, but this i what i do:

1. Open Pcmanfm-qt in a random directory. You need to  have the Side Pane activated and it should have bookmarks or the common folders (Home,Desktop,Trash,etc).
2. Change the color palette inside `lxqt-config-appearance`. If you had a darker one, set the default(white) palette. In the opposite case, invert the color palettes (from white to black/dark colors).
3. The pcmanfm-qt window that was opened prior the change of palette has changed all the colors, except the Side Pane colors.

##### Context

As far as i can recall, this did not happened in the previous pcmanfm-qt version (1.4.0), since i use this palette changes everyday.

##### System Information

* PcManFm-qt version:2.0
* Distribution & Version: Archlinux
* Qt Version: 6.7.0
* liblxqt Version: 2.0.0-1

Extra information:
`libfm-qt5 1.4.0-3` (AUR)

A picture showing what i see, in case my explanation is not much clear.

![pcman-issue-f](https://github.com/lxqt/pcmanfm-qt/assets/143142826/a2ea7a45-022b-448b-b302-68c0b8605865)

**Comment by Bluey26** [comment]
Yes, i was going to mention one: quassel , but its unrelated to LXQt and uses Qt5 as far as i know. 

Thank you very much

**Comment by tsujan** [comment]
OK, contrary to my expectation, I can't reproduce it here.

You said you had libfm-qt5 1.4.0-3 (AUR). That's suspicious; pcmafm-qt 2.0 needs libfm-qt 2.0.

**Comment by Bluey26** [comment]
> OK, contrary to my expectation, I can't reproduce it here.
> 
> You said you had libfm-qt5 1.4.0-3 (AUR). That's suspicious; pcmafm-qt 2.0 needs libfm-qt 2.0.

Oh, yes. I have `libfm-qt 2.0.2-1` but also the qt5 compatibility package `libfm-qt5 1.4.0-3`

**Comment by tsujan** [comment]
Haha... it's so tricky. It doesn't happen here if I disable the desktop mode, but with the desktop mode and if the window is on the current desktop, yes, I can see it. Qt does weird thing!

**Comment by Bluey26** [comment]
> Haha... it's so tricky. It doesn't happen here if I disable the desktop mode, but with the desktop mode and if the window is on the current desktop, yes, I can see it. Qt does weird thing!

Yes, i have pcmanfm-qt running as:

`pcmanfm-qt --desktop --profile=lxqt` (labwc session)

**Comment by tsujan** [comment]
I checked the code. The interesting thing is that I'd predicted it and added a small workaround for it years ago, but that workaround doesn't work completely with Qt6, although it might have worked with Qt5 (I remember that I'd checked it with Qt5).

**Comment by tsujan** [comment]
It's fixed here by this simple change: https://github.com/lxqt/libfm-qt/pull/980

But I'd be very grateful if you could test the patch too. Who knows what tricks Qt6 can play? ;)

**Comment by Bluey26** [comment]
> It's fixed here by this simple change: #980
> 
> But I'd be very grateful if you could test the patch too. Who knows what tricks Qt6 can play? ;)

For some reason i dont see any changes in here. (I rebooted the system after instalation)

I did the following:

Cloned this repo:
https://gitlab.archlinux.org/archlinux/packaging/packages/libfm-qt

Then i modified the  PKGBUILD:

```
source=("git+https://github.com/lxqt/libfm-qt#branch=sidepane_style_change_qt6")
sha256sums=('SKIP')
```
and inside the build part:

`cmake -B build -S "$srcdir/$pkgname-$pkgver" \` ---> `cmake -B build -S "$srcdir/$pkgname"`


.SRCINFO :
```
source = git+https://github.com/lxqt/libfm-qt#branch=sidepane_style_change_qt6
sha256sums = SKIP
```

I think that i cloned correctly. I used that package and not the git branch because i was having issues with names and dependency requirements (that are fulfilled by the arch package).

I will try again to see what happens.

**Comment by Bluey26** [comment]
For some reason it does not work in here.

I just noticed, in the process, that there has been a qt upgrade in archlinux. Now my version is
`Qt 6.7.1`

and that a few lxqt packages were updated too, including this one: https://archlinux.org/packages/extra/x86_64/libfm-qt/

During `makepkg` with the changes i have specified in the previous comment, i have noticed this messages:

```
[ 77%] Building CXX object src/CMakeFiles/fm-qt6.dir/appmenuview.cpp.o
/home/USER_NAME/libfm-qt/src/libfm-qt/src/appmenuview.cpp: In member function ‘void Fm::AppMenuView::addMenuItems(QStandardItem*, MenuCacheDir*)’:
/home/USER_NAME/libfm-qt/src/libfm-qt/src/appmenuview.cpp:98:29: warning: cast between incompatible function types from ‘gboolean (*)(MenuCacheItem*)’ {aka ‘int (*)(MenuCacheItem*)’} to ‘GDestroyNotify’ {aka ‘void (*)(void*)’} [-Wcast-function-type]
   98 |     g_slist_free_full(list, (GDestroyNotify)menu_cache_item_unref);
      |                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

```
[ 80%] Building CXX object src/CMakeFiles/fm-qt6.dir/xdndworkaround.cpp.o
In file included from /usr/include/qt6/QtCore/6.7.1/QtCore/private/qobject_p.h:28,
                 from /usr/include/qt6/QtGui/6.7.1/QtGui/private/qdnd_p.h:27,
                 from /home/USER_NAME/libfm-qt/src/libfm-qt/src/xdndworkaround.cpp:33:
/usr/include/qt6/QtCore/6.7.1/QtCore/private/qproperty_p.h:310:16: warning: ISO C++ prohibits anonymous structs [-Wpedantic]
  310 |         struct {
      |      
```

I dont know if they are related to this, they dont seem to break the process and the program compiles properly.

**Comment by tsujan** [comment]
> During makepkg with the changes i have specified in the previous comment, i have noticed this messages...

They aren't related to this.

Make sure that, after the upgrade, pcmanfm-qt is completely terminated (check it with Qps) and then started.

**Comment by Bluey26** [comment]
> I succeeded in reproducing it again after trying 4 times. Suspecting a timing issue with Qt6, I made a change to the patch. Please try again, by compiling the branch.
> 
> Sorry for bothering you with this, but as you see, it's somehow tricky: a user may reproduce it easily, while another user may not.

Sorry for the delay.

Now i can verify it works in my side.

I compiled it again(the same branch) and after stopping and running again Desktop Module, i can see it works properly.
Maybe something in the 2 commits you have added made it work in my side.

Thank you very much!

**Comment by tsujan** [comment]
Thanks a lot for reporting and especially for testing!

Since it has a random nature, if you encounter a counterexample, please don't hesitate to tell me.

BTW, lxqt-panel crashed here after several palette changes, but its backtrace showed that the problem was in Qt6. The word "regression" that you used in the report title may be a good description, although it's in Qt6, not in LXQt. However, pcmanfm-qt never crashed, and its side pane was OK with the revised patch after 10 palette changes.

**Comment by Bluey26** [comment]
> Thanks a lot for reporting and especially for testing!
> 
> Since it has a random nature, if you encounter a counterexample, please don't hesitate to tell me.
> 
> BTW, lxqt-panel crashed here after several palette changes, but its backtrace showed that the problem was in Qt6. The word "regression" that you used in the report title may be a good description, although it's in Qt6, not in LXQt. However, pcmanfm-qt never crashed, and its side pane was OK with the revised patch after 10 palette changes.

Strange, i have not seen a lxqt-panel crash in some time. Even i cannot see one of those in `coredumpctl`. Just for the record i am using: https://github.com/LXQt-Marcus-Fork/lxqt-panel/tree/wlroots-taskbar

Yes, i will report if i find some kind of drawback or problem with the commit, so far everything looks OK.
It could be a qt6 problem, yes. I used the word regression because i knew it was working in 1.4 but not in 2.0 , but i was not aware of which caused it.

Fortunately the only coredumps i see (related to LXQt) are `lxqt-config-monitor` and `lxqt-config-input` but those do not work in wayland at the moment, so its expected to crash.

**Comment by tsujan** [comment]
> Just for the record i am using....

Like you, I'm under LXQt+LabWC and use that patch :)

The problem I encountered in the panel was very random, and I'm 99% sure that its cause was in Qt6.

**Comment by stefonarch** [comment]
> Fortunately the only coredumps i see (related to LXQt) are `lxqt-config-monitor` and `lxqt-config-input` but those do not work in wayland at the moment (at least under LabWC), so its expected to crash.

For both there are PRs ready, showing a message instead of crashing.

![immagine](https://github.com/lxqt/libfm-qt/assets/10681413/5a585980-8a60-44b8-93dc-441dfea73ceb)

`lxqt-config-monitor` is working on kwin_wayland but lacks the scale setting for each monitor.

**Comment by Bluey26** [comment]
Hello @tsujan i just updated my system today and i noticed that qt did an upgrade.

After restarting my system and changing my LXQt theme palette i noticed that the aforementioned issue on the Side-Pane started to happen again, i was wondering if the qt code had made some kind of revert in regards of this. I will try to compile a previous commit and see if it works in there (before this patch).

**Comment by tsujan** [comment]
> i was wondering if the qt code had made some kind of revert in regards of this.

They usually don't revert but make more regressions ;) Please wait until @stefonarch or I upgrade our Qt to 6.7.2 — it might take a little longer for me because I have Manjaro Testing.

**Comment by stefonarch** [comment]
Updated now, all fine also after a session restart.

**Comment by Bluey26** [comment]
https://github.com/lxqt/libfm-qt/assets/143142826/d7008a97-268b-4fd7-9b3d-22980c8666a5

Here's a video, i don't understand why its happening in here.

To follow the video:

Dark (Fine) -> Light -> Dark -> Light

**Comment by stefonarch** [comment]
You could test it on an a clean user (I use just startlxqtlabwc from a tty with my testuser).

**Comment by tsujan** [comment]
> How can i do that?

I'd say there's no need to it. Since you're able to reproduce the issue easily, we'll need your current system for tests. I'm preparing a PR...

**Comment by tsujan** [comment]
@Bluey26
Please try https://github.com/lxqt/libfm-qt/pull/990. Make sure pcmanfm-qt's process is stopped completely before you do your tests.

**Comment by Bluey26** [comment]
> @Bluey26 Please try #990. Make sure pcmanfm-qt's process is stopped completely before you do your tests.

Awesome! I restarted the "Desktop" module after installing it the usual way(archlinux pkgbuilds) and it worked!.

I also restarted my system and tested it again, and it works :)

Thank you very much!

**Comment by tsujan** [comment]
Thanks for testing!

Because of the random aspect of the problem — which is supposedly removed by the PR — please do more tests and report back if you see it again. I'll merge the PR soon because it's more precise than the previous methods.

**Comment by Bluey26** [comment]
Hi, im sorry but the issue started to happen in my side again. I installed the OS from scratch in a new disk and i noticed this started to happen(2 days ago i think).

I compiled from the git master the libfm-qt package, using:
`
source=('git+https://github.com/lxqt/libfm-qt')`

without luck, i guess Qt has changed something again.

**Comment by tsujan** [comment]
>i guess Qt has changed something again.

Which version of Qt?

**Comment by Bluey26** [comment]
> Which version of Qt?

Qt: 6.7.2 (`qt6-base 6.7.2-1`)

**Comment by tsujan** [comment]
> Qt: 6.7.2 (qt6-base 6.7.2-1)

That's the same version the patch was made for, and I have it here too.

I think, for some reason, you don't use the git libfm-qt. Maybe you installed it correctly but didn't restart pcmanfm-qt after that.

**Comment by Bluey26** [comment]
> you don't use the git libfm-qt.

Indeed, that was the problem. I compiled the package using the old branch(last release) and i changed the PKGBUILD after, so i was confused.

Now i have re-compiled it and installed. After rebooting and changing the color palettes, everything seems to work.

Thank you!!
