### ISSUE TITLE
Drag and Drop root web link from browser to Desktop does nothing.

### ISSUE THREAD

**Issue by humpity** [lxqt/libfm-qt#987]
Creating a web shortcut on the Desktop by DND from the browser address field icon to the Desktop does not work if the web address is just the root domain e.g www.google.com.

##### Expected Behavior
A 'shortcut' i.e something.desktop file should be created in the Desktop folder with URL=<web address>.

##### Current Behavior
Nothing happens if the web address is just the root domain e.g www.google.com.

It works properly if the web address is extended (e.g has a file name) e.g
www.google.com/index.html

##### Possible Solution
A workaround is to add something at the end e.g "/index.html" but not all
websites accept this.

##### Steps to Reproduce (for bugs)
1.  Type "google.com" in the address bar of your browser, enter.
2. Drag and Drop the address bar icon (e.g padlock, or whatever) onto the Desktop, choose 'Create symlink here'.
3. See if a web shortcut is created on your Desktop.

##### Context
Creating browser shortcuts on the Desktop.

##### System Information
* Distribution & Version: Lubuntu 24.04
* Kernel: 6.8.0-31
* Qt Version: 1.4.0
* libqtxdg Version: libqt5xdg3 3.12.0-0ubuntu6
* 
Extra info -
Bug occurs for different browser, whether snap or deb, and whether xdg-desktop-portal is installed or not.
(suspect FileTransferJob::setDestDirPath not getting a filename for the desktop file).

**Comment by tsujan** [comment]
Thanks for the report!

The problem is that, in such cases, GLib gives just a slash for the base name, and so, `g_file_get_child()` fails inside `FileTransferJob::setDestDirPath()`. A simple workaround is the removal of the trailing slash, but it results in this when  `google.com` is entered:

```
[Desktop Entry]
Type=Link
Name=/
Icon=text-html
URL=https://www.google.com/
```

This shortcut is valid and works, but its name is weird. So, a better solution may be needed.

**Comment by stefonarch** [comment]
Under wayland I noticed that the "copy" works for some webpage like https://lxqt-project.org/downloads/ , for some it doesn't include the css  if clicked.

**Comment by tsujan** [comment]
Copying is done by GLib and is almost useless in this case — it's a browser job. But making shortcuts is done by libfm-qt, whose code doesn't cover a special case. I'll make a PR soon.

**Comment by tsujan** [comment]
The fix is here: https://github.com/lxqt/libfm-qt/pull/988
