### ISSUE TITLE
Truncated text in prompt for executing with font bigger than 12px

### ISSUE THREAD

**Issue by stefonarch** [lxqt/libfm-qt#993]
See this, Dejavu sans:

12px:
![immagine](https://github.com/lxqt/libfm-qt/assets/10681413/8fbb78d6-ea08-47f7-a960-d3355f4da68e)

13px
![immagine](https://github.com/lxqt/libfm-qt/assets/10681413/cdafae79-f660-4684-8488-342851b6a642)

16px:

![immagine](https://github.com/lxqt/libfm-qt/assets/10681413/c1cb3e29-2456-4a10-b722-06c357fb1ef0)

##### Expected Behavior

The entire text is displayed.
##### Current Behavior

It's not.

##### System Information

* Distribution & Version: all

**Comment by tsujan** [comment]
I'd seen it in one of my apps too; should check what kind of workaround I used there — it's an old Qt issue.
