### ISSUE TITLE
Save dialog: Filename character replaced with underscores

### ISSUE THREAD

**Issue by isf63** [lxqt/libfm-qt#996]
I have files with colons (`:`) and I tried to overwrite them with the Save As dialog. Unexpectedly the colons were replaced with underscores.

##### Steps to Reproduce (for bugs)
1. Open the Save As dialog
2. Include a colon in the filename and save
3. Colon is replaced with an underscore
4. 

##### Context
This may affect other characters, as well as other dialogs

##### System Information
* Distribution & Version: Arch Linux
* Qt Version: 6.7.2, 5.15.14+kde+r143
* libqtxdg Version: 4.0.0, 3.12.0-2
* Package version: 2.0.2.r15.g5b6b8dd, 1.4.0-3

**Comment by isf63** [comment]
Actually, I can only produce this behavior under Firefox saving, so it may be specific to xdg-desktop-portal-lxqt.

**Comment by tsujan** [comment]
It isn't related to `xdg-desktop-portal-lxqt` either, because Chromium also uses it and doesn't replace colon with underscore. But yes, Firefox does.

**Comment by isf63** [comment]
To clarify, it's Firefox's behavior?

**Comment by tsujan** [comment]
> To clarify, it's Firefox's behavior?

Everything shows that it is: `libfm-qt` and `xdg-desktop-portal-lxqt` are the same, but colons are replaced only when Firefox is used.

Anyway, this behavior is definitely not caused by `libfm-qt`. If you see a different behavior, e.g., with KDE's portal, please open a report at `xdg-desktop-portal-lxqt`.

**Comment by isf63** [comment]
This was reported elsewhere with Firefox, it's for security reasons. https://support.mozilla.org/bm/questions/1439267

**Comment by tsujan** [comment]
Oh, thanks for the info!

I guessed that it might be related to MS Windows, although that page is about `%`, not `:`.
