### ISSUE TITLE
Layout issue with file-props "Device Usage"

### ISSUE THREAD

**Issue by isf63** [lxqt/libfm-qt#999]
##### Expected Behavior
The "Device Usage" progress bar gets the preferred amount of vertical space always, and resizing the window doesn't affect it.

##### Current Behavior
With a large enough font size, the progress bar's vertical space is slightly variable when the window is resized. Also on "Fusion", this sometimes makes the inner text appear scrunched. On various Kvantum themes the text jumps from the right to the top.

##### Possible Solution
I tried various changes to file-props.ui but couldn't figure it out.

##### Steps to Reproduce (for bugs)
1. Set font size to a large enough point size.
2. Resize the file properties window.

##### Context
Minor UI issue

##### System Information

* Distribution & Version: 
* Kernel: 
* Qt Version: 
* libqtxdg Version: 
* lxqt-build-tools Version: 
* Package version:

**Comment by tsujan** [comment]
Not our problem.

Qt6 has got problems related to resizing, especially under Wayland (where the possibility of resizing to a size smaller than the minimum allowed size is a total disaster).

**Comment by tsujan** [comment]
Your report reminded me of another, more serious, longstanding Qt issue whose workaround was easy. See https://github.com/lxqt/libfm-qt/pull/1001
